#!/usr/bin/env python3
"""Generate bilingual ROM text; reject stale sources, placeholders and wide lines."""
import json,re
from collections import Counter
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
FONT=re.search(r'gFontNormalLatinGlyphWidths\[\]\s*=\s*\{([^}]+)',(ROOT/'src/fonts.c').read_text(),re.S).group(1)
WIDTHS=[int(n) for n in re.findall(r'\d+',FONT)]
CHARMAP={ch:int(n,16) for ch,n in re.findall(r"^'(.)'\s*=\s*([0-9A-Fa-f]{2})\s*$",(ROOT/'charmap.txt').read_text(),re.M)}
CHARMAP["'"]=0xB4
RESERVE={'PLAYER':7*8,'RIVAL':7*8,'STR_VAR_1':12*8,'STR_VAR_2':18*8,'STR_VAR_3':20*8}
def width(s):
    total=0
    for token in re.findall(r'\{[^}]+\}|.',s):
        if token.startswith('{'): total+=RESERVE.get(token[1:-1],0)
        else:
            if token not in CHARMAP: raise ValueError(f'Unsupported glyph: {token!r}')
            total+=WIDTHS[CHARMAP[token]]
    return total

def wrap(text):
    pages=[]
    for paragraph in text.split('|'):
        lines=[];line=''
        for word in paragraph.split():
            if width(word)>208:raise ValueError('Word too wide: '+word)
            candidate=(line+' '+word).strip()
            if width(candidate)>208:lines.append(line);line=word
            else:line=candidate
        if line:lines.append(line)
        pages.extend('\\n'.join(lines[i:i+2]) for i in range(0,len(lines),2))
    return '\\p'.join(pages)+'$'

def quote(text): return text.replace('"','\\"')
def main():
    catalog=json.loads((ROOT/'docs/localization/story_catalog.json').read_text())
    asm=['@ Generated by tools/localization/generate_story.py. Edit the catalog instead.']
    header=['// Generated by tools/localization/generate_story.py.','']
    pairs=[];cache={};seen=set()
    for entry in catalog:
        text=wrap(entry['en'])
        worst=re.sub(r'\{([^}]+)\}',lambda m:'M'*(RESERVE.get(m[1],0)//8),text).replace('\\n','X').replace('\\p','X')
        if len(worst)>1000:raise ValueError('Expanded dialogue exceeds gStringVar4: '+str(entry['id']))
        asm.extend([f"HE_English_{entry['id']}::",f'\t.string "{quote(text)}"',''])
        header.append(f"extern const u8 HE_English_{entry['id']}[];")
        for label in entry['labels']:
            if label['label'] in seen:raise ValueError('Duplicate label: '+label['label'])
            seen.add(label['label'])
            path=label['file'];source=cache.setdefault(path,(ROOT/path).read_text())
            m=re.search(r'(?m)^'+re.escape(label['label'])+r'::?\s*\n((?:\s*\.string[^\n]*\n)+)',source)
            if not m:raise ValueError('Missing label: '+label['label'])
            actual=''.join(re.findall(r'\.string\s+"(.*)"',m.group(1)))
            if actual!=label['pt']: raise ValueError('Stale source: '+label['label'])
            if Counter(re.findall(r'\{[^}]+\}',actual))!=Counter(re.findall(r'\{[^}]+\}',text)):
                raise ValueError('Placeholder mismatch: '+label['label'])
            asm.append('\t.global '+label['label'])
            header.append('extern const u8 '+label['label']+'[];')
            pairs.append('    {HE_English_'+str(entry['id'])+', '+label['label']+'},')
    header.extend(['','static const struct HeTranslation sStoryTranslations[] = {',*pairs,'};',''])
    (ROOT/'data/text/hoenn_story_en.inc').write_text('\n'.join(asm)+'\n')
    (ROOT/'src/data/hoenn_story_localization.h').write_text('\n'.join(header))
    ui=json.loads((ROOT/'docs/localization/ui_catalog.json').read_text())
    out=['// Reviewed custom interface translations.']
    for i,e in enumerate(ui):
        if i>=36 and len(e['en'])>37:raise ValueError('Opening caption too wide: '+e['en'])
        for lang in ['pt','en']:out.append(f'static const u8 sStoryUi{i}{lang}[] = _(\"{e[lang]}\");')
    out+=['static const struct HeTranslation sStoryUiTranslations[] = {']
    out += [f'    {{sStoryUi{i}en, sStoryUi{i}pt}},' for i in range(len(ui))]
    out+=['};','']
    (ROOT/'src/data/hoenn_ui_localization.h').write_text('\n'.join(out))
    print(f'Generated {len(catalog)} English texts for {len(pairs)} source labels; placeholders and 208px line widths verified.')
if __name__=='__main__':main()
