Common_EventScript_FindItem::
	callnative GetItemBallIdAndAmountFromTemplate
	finditem VAR_RESULT VAR_0x8009
	end

MauvilleCity_EventScript_ItemXSpeed::
	finditem ITEM_X_SPEED
	end

RustboroCity_EventScript_ItemXDefend::
	finditem ITEM_X_DEFEND
	end

Route104_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route104_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

Route104_EventScript_ItemXAccuracy::
	finditem ITEM_X_ACCURACY
	end

Route104_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

GraniteCave_1F_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

PetalburgWoods_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

PetalburgWoods_EventScript_ItemXAttack::
	finditem ITEM_X_ATTACK
	end

PetalburgWoods_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

PetalburgWoods_EventScript_ItemParalyzeHeal::
	finditem ITEM_PARALYZE_HEAL
	end
