#include "global.h"
#include "constants/flags.h"
#include "constants/vars.h"
#include "constants/species.h"
#include "sinnoh_chapter.h"
#include "event_data.h"
#include "regions.h"
#include "constants/regions.h"
EWRAM_DATA u16 gSiAdminKey = 0;
void SiInRegion(void) { gSpecialVar_Result = (GetCurrentRegion() == REGION_SINNOH); }
bool8 SiAdminUnlocked(void) {
#if SI_ADMIN_BUILD
    return gSiAdminKey == 0x71A9;
#else
    return FALSE;
#endif
}

#include "overworld.h"
#include "constants/maps.h"
#include "constants/vars.h"
#include "constants/flags.h"
#include "constants/heal_locations.h"
unsigned char SiIsSeason(void) { return VarGet(VAR_HE_SEASON) == 1; }
void SiInitializeSeason(void)
{
    SetWarpDestination(MAP_GROUP(MAP_TWINLEAF_TOWN), MAP_NUM(MAP_TWINLEAF_TOWN), WARP_ID_NONE, 9, 20);
    WarpIntoMap();
    SetLastHealLocationWarp(HEAL_LOCATION_SI_SANDGEMTOWN);
    VarSet(VAR_SI_STAGE, 0);
    FlagSet(FLAG_RECEIVED_RUNNING_SHOES);
    FlagSet(FLAG_SYS_B_DASH);
}

#include "constants/layouts.h"
static const u8 sSiMapName_LAYOUT_SI_TWINLEAFTOWN[] = _("TWINLEAF TOWN");
static const u8 sSiMapName_LAYOUT_SI_SANDGEMTOWN[] = _("SANDGEM TOWN");
static const u8 sSiMapName_LAYOUT_SI_JUBILIFECITY[] = _("JUBILIFE CITY");
static const u8 sSiMapName_LAYOUT_SI_OREBURGHCITY[] = _("OREBURGH CITY");
static const u8 sSiMapName_LAYOUT_SI_ROUTE201[] = _("ROUTE201");
static const u8 sSiMapName_LAYOUT_SI_ROUTE202[] = _("ROUTE202");
static const u8 sSiMapName_LAYOUT_SI_ROUTE203[] = _("ROUTE203");
static const u8 sSiMapName_LAYOUT_SI_VERITYLAKEFRONT[] = _("VERITY LAKEFRONT");
static const u8 sSiMapName_LAYOUT_SI_LAKEVERITY[] = _("LAKE VERITY");
static const u8 sSiMapName_LAYOUT_SI_OREBURGHGATE_1F[] = _("OREBURGH GATE 1F");
static const u8 sSiMapName_LAYOUT_SI_OREBURGHMINE_B1F[] = _("OREBURGH MINE B1F");
static const u8 sSiMapName_LAYOUT_SI_OREBURGHMINE_B2F[] = _("OREBURGH MINE B2F");
static const u8 sSiMapName_LAYOUT_SI_TWINLEAFTOWN_MAINHOUSE_1F[] = _("TWINLEAF TOWN MAIN HO");
static const u8 sSiMapName_LAYOUT_SI_TWINLEAFTOWN_MAINHOUSE_2F[] = _("TWINLEAF TOWN MAIN HO");
static const u8 sSiMapName_LAYOUT_SI_TWINLEAF_TOWN_RIVALSHOUSE_F1[] = _("TWINLEAF TOWN RIVALS ");
static const u8 sSiMapName_LAYOUT_SI_TWINLEAF_TOWN_RIVALSHOUSE_F2[] = _("TWINLEAF TOWN RIVALS ");
static const u8 sSiMapName_LAYOUT_SI_TWINLEAFTOWN_HAOUSE1[] = _("TWINLEAF TOWN HAOUSE1");
static const u8 sSiMapName_LAYOUT_SI_TWINLEAFTOWN_HOUSE2[] = _("TWINLEAF TOWN HOUSE2");
static const u8 sSiMapName_LAYOUT_SI_SANDGEMTOWN_RIVALHOUSE_F1[] = _("SANDGEM TOWN RIVAL HO");
static const u8 sSiMapName_LAYOUT_SI_SANDGEMTOWN_RIVALHOUSE_F2[] = _("SANDGEM TOWN RIVAL HO");
static const u8 sSiMapName_LAYOUT_SI_SANDGEMTOWN_HOUSE1[] = _("SANDGEM TOWN HOUSE1");
static const u8 sSiMapName_LAYOUT_SI_SANDGEMTOWN_POKEMONCENTER_1F[] = _("SANDGEM TOWN POKEMON ");
static const u8 sSiMapName_LAYOUT_SI_SANDGEMTOWN_POKEMONCENTER_2F[] = _("SANDGEM TOWN POKEMON ");
static const u8 sSiMapName_LAYOUT_SI_SANDGEMTOWN_MART[] = _("SANDGEM TOWN MART");
static const u8 sSiMapName_LAYOUT_SI_JUBILIFECITY_POKEMONSCHOOL[] = _("JUBILIFE CITY POKEMON");
static const u8 sSiMapName_LAYOUT_SI_JUBILIFECITY_JUBILIFETV_F1[] = _("JUBILIFE CITY JUBILIF");
static const u8 sSiMapName_LAYOUT_SI_JUBILIFECITY_JUBILIFETV_F2[] = _("JUBILIFE CITY JUBILIF");
static const u8 sSiMapName_LAYOUT_SI_JUBILIFECITY_JUBILIFETV_F3[] = _("JUBILIFE CITY JUBILIF");
static const u8 sSiMapName_LAYOUT_SI_JUBILIFECITY_JUBILIFETV_F4[] = _("JUBILIFE CITY JUBILIF");
static const u8 sSiMapName_LAYOUT_SI_JUBILIFECITY_POKETCHCOMPANY_F1[] = _("JUBILIFE CITY POKETCH");
static const u8 sSiMapName_LAYOUT_SI_JUBILIFECITY_POKETCHCOMPANY_F2[] = _("JUBILIFE CITY POKETCH");
static const u8 sSiMapName_LAYOUT_SI_JUBILIFECITY_POKETCHCOMPANY_F3[] = _("JUBILIFE CITY POKETCH");
static const u8 sSiMapName_LAYOUT_SI_JUBILIFECITY_FLAT1_F1[] = _("JUBILIFE CITY FLAT1 F");
static const u8 sSiMapName_LAYOUT_SI_JUBILIFECITY_FLAT1_F2[] = _("JUBILIFE CITY FLAT1 F");
static const u8 sSiMapName_LAYOUT_SI_JUBILIFECITY_FLAT1_F3[] = _("JUBILIFE CITY FLAT1 F");
static const u8 sSiMapName_LAYOUT_SI_JUBILIFECITY_FLAT2_F1[] = _("JUBILIFE CITY FLAT2 F");
static const u8 sSiMapName_LAYOUT_SI_JUBILIFECITY_FLAT2_F2[] = _("JUBILIFE CITY FLAT2 F");
static const u8 sSiMapName_LAYOUT_SI_JUBILIFECITY_FLAT2_F3[] = _("JUBILIFE CITY FLAT2 F");
static const u8 sSiMapName_LAYOUT_SI_JUBILIFECITY_FLAT3_F1[] = _("JUBILIFE CITY FLAT3 F");
static const u8 sSiMapName_LAYOUT_SI_JUBILIFECITY_FLAT3_F2[] = _("JUBILIFE CITY FLAT3 F");
static const u8 sSiMapName_LAYOUT_SI_JUBILIFECITY_FLAT3_F3[] = _("JUBILIFE CITY FLAT3 F");
static const u8 sSiMapName_LAYOUT_SI_JUBILIFECITY_POKEMONCENTER_1F[] = _("JUBILIFE CITY POKEMON");
static const u8 sSiMapName_LAYOUT_SI_JUBILIFECITY_POKEMONCENTER_2F[] = _("JUBILIFE CITY POKEMON");
static const u8 sSiMapName_LAYOUT_SI_JUBILIFECITY_MART[] = _("JUBILIFE CITY MART");
static const u8 sSiMapName_LAYOUT_SI_OREBURGHCITY_FLAT1_F1[] = _("OREBURGH CITY FLAT1 F");
static const u8 sSiMapName_LAYOUT_SI_OREBURGHCITY_FLAT1_F2[] = _("OREBURGH CITY FLAT1 F");
static const u8 sSiMapName_LAYOUT_SI_OREBURGHCITY_FLAT2_F1[] = _("OREBURGH CITY FLAT2 F");
static const u8 sSiMapName_LAYOUT_SI_OREBURGHCITY_FLAT2_F2[] = _("OREBURGH CITY FLAT2 F");
static const u8 sSiMapName_LAYOUT_SI_OREBURGHCITY_FLAT3_F1[] = _("OREBURGH CITY FLAT3 F");
static const u8 sSiMapName_LAYOUT_SI_OREBURGHCITY_FLAT3_F2[] = _("OREBURGH CITY FLAT3 F");
static const u8 sSiMapName_LAYOUT_SI_OREBURGHCITY_HOUSE1[] = _("OREBURGH CITY HOUSE1");
static const u8 sSiMapName_LAYOUT_SI_OREBURGHCITY_HOUSE2[] = _("OREBURGH CITY HOUSE2");
static const u8 sSiMapName_LAYOUT_SI_OREBURGHCITY_HOUSE3[] = _("OREBURGH CITY HOUSE3");
static const u8 sSiMapName_LAYOUT_SI_OREBURGHCITY_GYM[] = _("OREBURGH CITY GYM");
static const u8 sSiMapName_LAYOUT_SI_OREBURGHCITY_POKEMONCENTER_1F[] = _("OREBURGH CITY POKEMON");
static const u8 sSiMapName_LAYOUT_SI_OREBURGHCITY_POKEMONCENTER_2F[] = _("OREBURGH CITY POKEMON");
static const u8 sSiMapName_LAYOUT_SI_OREBURGHCITY_MART[] = _("OREBURGH CITY MART");
static const u8 sSiMapName_LAYOUT_SI_SANDGEMLAB[] = _("SANDGEM LAB");
static const u8 sSiMapName_LAYOUT_SI_OREBURGHMUSEUM[] = _("OREBURGH MUSEUM");
static const u8 sSiMapName_LAYOUT_SI_FLOAROMATOWN[] = _("FLOAROMA TOWN");
static const u8 sSiMapName_LAYOUT_SI_ETERNACITY[] = _("ETERNA CITY");
static const u8 sSiMapName_LAYOUT_SI_HEARTHOMECITY[] = _("HEARTHOME CITY");
static const u8 sSiMapName_LAYOUT_SI_SOLACEONTOWN[] = _("SOLACEON TOWN");
static const u8 sSiMapName_LAYOUT_SI_CELESTICTOWN[] = _("CELESTIC TOWN");
static const u8 sSiMapName_LAYOUT_SI_VEILSTONECITY[] = _("VEILSTONE CITY");
static const u8 sSiMapName_LAYOUT_SI_PASTORIACITY[] = _("PASTORIA CITY");
static const u8 sSiMapName_LAYOUT_SI_CANALAVECITY[] = _("CANALAVE CITY");
static const u8 sSiMapName_LAYOUT_SI_SNOWPOINTCITY[] = _("SNOWPOINT CITY");
static const u8 sSiMapName_LAYOUT_SI_SUNYSHORECITY[] = _("SUNYSHORE CITY");
static const u8 sSiMapName_LAYOUT_SI_POKMONLEAGUE[] = _("POKMON LEAGUE");
static const u8 sSiMapName_LAYOUT_SI_ROUTE204[] = _("ROUTE204");
static const u8 sSiMapName_LAYOUT_SI_ROUTE205_NORTH[] = _("ROUTE205 NORTH");
static const u8 sSiMapName_LAYOUT_SI_ROUTE205_SOUTH[] = _("ROUTE205 SOUTH");
static const u8 sSiMapName_LAYOUT_SI_ROUTE206[] = _("ROUTE206");
static const u8 sSiMapName_LAYOUT_SI_ROUTE207[] = _("ROUTE207");
static const u8 sSiMapName_LAYOUT_SI_ROUTE208[] = _("ROUTE208");
static const u8 sSiMapName_LAYOUT_SI_ROUTE209[] = _("ROUTE209");
static const u8 sSiMapName_LAYOUT_SI_ROUTE210_NORTH[] = _("ROUTE210 NORTH");
static const u8 sSiMapName_LAYOUT_SI_ROUTE210_SOUTH[] = _("ROUTE210 SOUTH");
static const u8 sSiMapName_LAYOUT_SI_ROUTE211_EAST[] = _("ROUTE211 EAST");
static const u8 sSiMapName_LAYOUT_SI_ROUTE211_WEST[] = _("ROUTE211 WEST");
static const u8 sSiMapName_LAYOUT_SI_ROUTE212_NORTH[] = _("ROUTE212 NORTH");
static const u8 sSiMapName_LAYOUT_SI_ROUTE212_SOUTH[] = _("ROUTE212 SOUTH");
static const u8 sSiMapName_LAYOUT_SI_ROUTE213[] = _("ROUTE213");
static const u8 sSiMapName_LAYOUT_SI_ROUTE214[] = _("ROUTE214");
static const u8 sSiMapName_LAYOUT_SI_ROUTE215[] = _("ROUTE215");
static const u8 sSiMapName_LAYOUT_SI_ROUTE216[] = _("ROUTE216");
static const u8 sSiMapName_LAYOUT_SI_ROUTE217[] = _("ROUTE217");
static const u8 sSiMapName_LAYOUT_SI_ROUTE218[] = _("ROUTE218");
static const u8 sSiMapName_LAYOUT_SI_ROUTE219[] = _("ROUTE219");
static const u8 sSiMapName_LAYOUT_SI_ROUTE220[] = _("ROUTE220");
static const u8 sSiMapName_LAYOUT_SI_ROUTE221[] = _("ROUTE221");
static const u8 sSiMapName_LAYOUT_SI_ROUTE222[] = _("ROUTE222");
static const u8 sSiMapName_LAYOUT_SI_ROUTE223[] = _("ROUTE223");
static const u8 sSiMapName_LAYOUT_SI_ROUTE224[] = _("ROUTE224");
static const u8 sSiMapName_LAYOUT_SI_ROUTE225[] = _("ROUTE225");
static const u8 sSiMapName_LAYOUT_SI_ROUTE226[] = _("ROUTE226");
static const u8 sSiMapName_LAYOUT_SI_ROUTE227[] = _("ROUTE227");
static const u8 sSiMapName_LAYOUT_SI_ROUTE228[] = _("ROUTE228");
static const u8 sSiMapName_LAYOUT_SI_ROUTE229[] = _("ROUTE229");
static const u8 sSiMapName_LAYOUT_SI_ROUTE230[] = _("ROUTE230");
static const u8 sSiMapName_LAYOUT_SI_VALORLAKEFRONT[] = _("VALOR LAKEFRONT");
static const u8 sSiMapName_LAYOUT_SI_ACUITYLAKEFRONT[] = _("ACUITY LAKEFRONT");
static const u8 sSiMapName_LAYOUT_SI_FIGHTAREA[] = _("FIGHT AREA");
static const u8 sSiMapName_LAYOUT_SI_SURVIVALAREA[] = _("SURVIVAL AREA");
static const u8 sSiMapName_LAYOUT_SI_RESORTAREA[] = _("RESORT AREA");
static const u8 sSiMapName_LAYOUT_SI_LAKEVALOR[] = _("LAKE VALOR");
static const u8 sSiMapName_LAYOUT_SI_LAKEACUITY[] = _("LAKE ACUITY");
static const u8 sSiMapName_LAYOUT_SI_VALLEYWINDWORKS[] = _("VALLEY WINDWORKS");
static const u8 sSiMapName_LAYOUT_SI_ETERNAFOREST[] = _("ETERNA FOREST");
static const u8 sSiMapName_LAYOUT_SI_FLOAROMAMEADOW[] = _("FLOAROMA MEADOW");
static const u8 sSiMapName_LAYOUT_SI_RAVAGEDPATH[] = _("RAVAGED PATH");
static const u8 sSiMapName_LAYOUT_SI_MTCORONET_B1F[] = _("MT CORONET B1F");
static const u8 sSiMapName_LAYOUT_SI_MTCORONET_1F_SOUTH[] = _("MT CORONET 1F SOUTH");
static const u8 sSiMapName_LAYOUT_SI_MTCORONET_1F_NORTH_ROOM1[] = _("MT CORONET 1F NORTH R");
static const u8 sSiMapName_LAYOUT_SI_MTCORONET_1F_NORTH_ROOM2[] = _("MT CORONET 1F NORTH R");
static const u8 sSiMapName_LAYOUT_SI_OLDCHATEAU_ENTRANCE[] = _("OLD CHATEAU ENTRANCE");
static const u8 sSiMapName_LAYOUT_SI_OLDCHATEAU_SIDEROOM_1[] = _("OLD CHATEAU SIDE ROOM");
static const u8 sSiMapName_LAYOUT_SI_OLDCHATEAU_SIDEROOM_2[] = _("OLD CHATEAU SIDE ROOM");
static const u8 sSiMapName_LAYOUT_SI_OLDCHATEAU_DININGROOM[] = _("OLD CHATEAU DINING RO");
static const u8 sSiMapName_LAYOUT_SI_OLDCHATEAU_2F[] = _("OLD CHATEAU 2F");
static const u8 sSiMapName_LAYOUT_SI_ROUTE206_NORTH[] = _("ROUTE206 NORTH");
static const u8 sSiMapName_LAYOUT_SI_ROUTE206_SOUTH[] = _("ROUTE206 SOUTH");
static const u8 sSiMapName_LAYOUT_SI_ROUTE208_ACCESS[] = _("ROUTE208 ACCESS");
static const u8 sSiMapName_LAYOUT_SI_ROUTE209_ACCESS[] = _("ROUTE209 ACCESS");
static const u8 sSiMapName_LAYOUT_SI_ROUTE212_ACCESS[] = _("ROUTE212 ACCESS");
static const u8 sSiMapName_LAYOUT_SI_ROUTE213_ACCESS[] = _("ROUTE213 ACCESS");
static const u8 sSiMapName_LAYOUT_SI_ROUTE214_ACCESS[] = _("ROUTE214 ACCESS");
static const u8 sSiMapName_LAYOUT_SI_ROUTE215_ACCESS[] = _("ROUTE215 ACCESS");
static const u8 sSiMapName_LAYOUT_SI_ROUTE218_EAST[] = _("ROUTE218 EAST");
static const u8 sSiMapName_LAYOUT_SI_ROUTE218_WEST[] = _("ROUTE218 WEST");
static const u8 sSiMapName_LAYOUT_SI_ROUTE222_ACCESS[] = _("ROUTE222 ACCESS");
static const u8 sSiMapName_LAYOUT_SI_ROUTE225_ACCESS[] = _("ROUTE225 ACCESS");
static const u8 sSiMapName_LAYOUT_SI_ROUTE226_ACCESS[] = _("ROUTE226 ACCESS");
static const u8 sSiMapName_LAYOUT_SI_HOTELGRANDLAKE[] = _("HOTEL GRAND LAKE");
static const u8 sSiMapName_LAYOUT_SI_VALLEYWINDOWORKS_INDOOR[] = _("VALLEY WINDOWORKS IND");
static const u8 sSiMapName_LAYOUT_SI_ROUTE205_HOUSE[] = _("ROUTE205 HOUSE");
static const u8 sSiMapName_LAYOUT_SI_FLOAROMATOWN_HOUSE1[] = _("FLOAROMA TOWN HOUSE1");
static const u8 sSiMapName_LAYOUT_SI_FLOAROMATOWN_HOUSE2[] = _("FLOAROMA TOWN HOUSE2");
static const u8 sSiMapName_LAYOUT_SI_FLOAROMATOWN_FLOWERSHOP[] = _("FLOAROMA TOWN FLOWER ");
static const u8 sSiMapName_LAYOUT_SI_FLOAROMATOWN_POKEMONCENTER_1F[] = _("FLOAROMA TOWN POKEMON");
static const u8 sSiMapName_LAYOUT_SI_FLOAROMATWON_POKEMONCENTER_2F[] = _("FLOAROMA TWON POKEMON");
static const u8 sSiMapName_LAYOUT_SI_FLOAROMATOWN_MART[] = _("FLOAROMA TOWN MART");
static const u8 sSiMapName_LAYOUT_SI_FLOAROMAMEADOW_HOUSE[] = _("FLOAROMA MEADOW HOUSE");
static const u8 sSiMapName_LAYOUT_SI_ETERNACITY_FLAT1_F1[] = _("ETERNA CITY FLAT1 F1");
static const u8 sSiMapName_LAYOUT_SI_ETERNACITY_FLAT1_F2[] = _("ETERNA CITY FLAT1 F2");
static const u8 sSiMapName_LAYOUT_SI_ETERNACITY_FLAT1_F3[] = _("ETERNA CITY FLAT1 F3");
static const u8 sSiMapName_LAYOUT_SI_ETERNACITY_HERBSHOP[] = _("ETERNA CITY HERB SHOP");
static const u8 sSiMapName_LAYOUT_SI_ETERNACITY_UNDERGROUNDMANHOUSE[] = _("ETERNA CITY UNDERGROU");
static const u8 sSiMapName_LAYOUT_SI_ETERNACITY_CYCLESHOP[] = _("ETERNA CITY CYCLE SHO");
static const u8 sSiMapName_LAYOUT_SI_ETERNACITY_HOUSE1[] = _("ETERNA CITY HOUSE1");
static const u8 sSiMapName_LAYOUT_SI_ETERNACITY_HOUSE2[] = _("ETERNA CITY HOUSE2");
static const u8 sSiMapName_LAYOUT_SI_ETERNACITY_GYM[] = _("ETERNA CITY GYM");
static const u8 sSiMapName_LAYOUT_SI_ETERNACITY_POKEMONCENTER_F1[] = _("ETERNA CITY POKEMON C");
static const u8 sSiMapName_LAYOUT_SI_ETERNACITY_POKEMONCENTER_F2[] = _("ETERNA CITY POKEMON C");
static const u8 sSiMapName_LAYOUT_SI_ETERNACITY_MART[] = _("ETERNA CITY MART");
static const u8 sSiMapName_LAYOUT_SI_ETERNACITY_GALACTICBUILDING_1F[] = _("ETERNA CITY GALACTIC ");
static const u8 sSiMapName_LAYOUT_SI_ETERNACITY_GALACTICBUILDING_2F[] = _("ETERNA CITY GALACTIC ");
static const u8 sSiMapName_LAYOUT_SI_ETERNACITY_GALACTICBUILDING_3F[] = _("ETERNA CITY GALACTIC ");
static const u8 sSiMapName_LAYOUT_SI_ETERNACITY_GALACTICBUILDING_4F[] = _("ETERNA CITY GALACTIC ");
static const u8 sSiMapName_LAYOUT_SI_ETERNACITY_GALACTICBUILDING_B1F[] = _("ETERNA CITY GALACTIC ");
static const u8 sSiMapName_LAYOUT_SI_HEARTHOMECITY_POKEMONCENTER[] = _("HEARTHOME CITY POKEMO");
static const u8 sSiMapName_LAYOUT_SI_HEARTHOMECITY_MART[] = _("HEARTHOME CITY MART");
static const u8 sSiMapName_LAYOUT_SI_HEARTHOMECITY_HOUSE[] = _("HEARTHOME CITY HOUSE");
static const u8 sSiMapName_LAYOUT_SI_SOLACEONTOWN_POKEMONCENTER[] = _("SOLACEON TOWN POKEMON");
static const u8 sSiMapName_LAYOUT_SI_SOLACEONTOWN_MART[] = _("SOLACEON TOWN MART");
static const u8 sSiMapName_LAYOUT_SI_SOLACEONTOWN_HOUSE[] = _("SOLACEON TOWN HOUSE");
static const u8 sSiMapName_LAYOUT_SI_VEILSTONECITY_POKEMONCENTER[] = _("VEILSTONE CITY POKEMO");
static const u8 sSiMapName_LAYOUT_SI_VEILSTONECITY_MART[] = _("VEILSTONE CITY MART");
static const u8 sSiMapName_LAYOUT_SI_VEILSTONECITY_HOUSE[] = _("VEILSTONE CITY HOUSE");
static const u8 sSiMapName_LAYOUT_SI_PASTORIACITY_POKEMONCENTER[] = _("PASTORIA CITY POKEMON");
static const u8 sSiMapName_LAYOUT_SI_PASTORIACITY_MART[] = _("PASTORIA CITY MART");
static const u8 sSiMapName_LAYOUT_SI_PASTORIACITY_HOUSE[] = _("PASTORIA CITY HOUSE");
static const u8 sSiMapName_LAYOUT_SI_CELESTICTOWN_POKEMONCENTER[] = _("CELESTIC TOWN POKEMON");
static const u8 sSiMapName_LAYOUT_SI_CELESTICTOWN_MART[] = _("CELESTIC TOWN MART");
static const u8 sSiMapName_LAYOUT_SI_CELESTICTOWN_HOUSE[] = _("CELESTIC TOWN HOUSE");
static const u8 sSiMapName_LAYOUT_SI_CANALAVECITY_POKEMONCENTER[] = _("CANALAVE CITY POKEMON");
static const u8 sSiMapName_LAYOUT_SI_CANALAVECITY_MART[] = _("CANALAVE CITY MART");
static const u8 sSiMapName_LAYOUT_SI_CANALAVECITY_HOUSE[] = _("CANALAVE CITY HOUSE");
static const u8 sSiMapName_LAYOUT_SI_SNOWPOINTCITY_POKEMONCENTER[] = _("SNOWPOINT CITY POKEMO");
static const u8 sSiMapName_LAYOUT_SI_SNOWPOINTCITY_MART[] = _("SNOWPOINT CITY MART");
static const u8 sSiMapName_LAYOUT_SI_SNOWPOINTCITY_HOUSE[] = _("SNOWPOINT CITY HOUSE");
static const u8 sSiMapName_LAYOUT_SI_SUNYSHORECITY_POKEMONCENTER[] = _("SUNYSHORE CITY POKEMO");
static const u8 sSiMapName_LAYOUT_SI_SUNYSHORECITY_MART[] = _("SUNYSHORE CITY MART");
static const u8 sSiMapName_LAYOUT_SI_SUNYSHORECITY_HOUSE[] = _("SUNYSHORE CITY HOUSE");
static const u8 sSiMapName_LAYOUT_SI_FIGHTAREA_POKEMONCENTER[] = _("FIGHT AREA POKEMON CE");
static const u8 sSiMapName_LAYOUT_SI_FIGHTAREA_MART[] = _("FIGHT AREA MART");
static const u8 sSiMapName_LAYOUT_SI_FIGHTAREA_HOUSE[] = _("FIGHT AREA HOUSE");
static const u8 sSiMapName_LAYOUT_SI_RESORTAREA_POKEMONCENTER[] = _("RESORT AREA POKEMON C");
static const u8 sSiMapName_LAYOUT_SI_RESORTAREA_MART[] = _("RESORT AREA MART");
static const u8 sSiMapName_LAYOUT_SI_RESORTAREA_HOUSE[] = _("RESORT AREA HOUSE");
static const u8 sSiMapName_LAYOUT_SI_SURVIVALAREA_POKEMONCENTER[] = _("SURVIVAL AREA POKEMON");
static const u8 sSiMapName_LAYOUT_SI_SURVIVALAREA_MART[] = _("SURVIVAL AREA MART");
static const u8 sSiMapName_LAYOUT_SI_SURVIVALAREA_HOUSE[] = _("SURVIVAL AREA HOUSE");
static const u8 sSiMapName_LAYOUT_SI_HEARTHOMECITY_GYM[] = _("HEARTHOME CITY GYM");
static const u8 sSiMapName_LAYOUT_SI_VEILSTONECITY_GYM[] = _("VEILSTONE CITY GYM");
static const u8 sSiMapName_LAYOUT_SI_PASTORIACITY_GYM[] = _("PASTORIA CITY GYM");
static const u8 sSiMapName_LAYOUT_SI_CANALAVECITY_GYM[] = _("CANALAVE CITY GYM");
static const u8 sSiMapName_LAYOUT_SI_SNOWPOINTCITY_GYM[] = _("SNOWPOINT CITY GYM");
static const u8 sSiMapName_LAYOUT_SI_SUNYSHORECITY_GYM[] = _("SUNYSHORE CITY GYM");
static const u8 sSiMapName_LAYOUT_SI_CANALAVELIBRARY[] = _("CANALAVE LIBRARY");
static const u8 sSiMapName_LAYOUT_SI_VEILSTONEHQ[] = _("VEILSTONE HQ");
static const u8 sSiMapName_LAYOUT_SI_MTCORONETSUMMIT[] = _("MT CORONET SUMMIT");
static const u8 sSiMapName_LAYOUT_SI_SPEARPILLAR[] = _("SPEAR PILLAR");
static const u8 sSiMapName_LAYOUT_SI_DISTORTIONWORLD[] = _("DISTORTION WORLD");
static const u8 sSiMapName_LAYOUT_SI_HALLOFORIGIN[] = _("HALL OF ORIGIN");
static const u8 sSiMapName_LAYOUT_SI_TURNBACKCAVE[] = _("TURNBACK CAVE");
static const u8 sSiMapName_LAYOUT_SI_SNOWPOINTTEMPLE[] = _("SNOWPOINT TEMPLE");
static const u8 sSiMapName_LAYOUT_SI_VICTORYROAD[] = _("VICTORY ROAD");
static const u8 sSiMapName_LAYOUT_SI_LEAGUEAARON[] = _("LEAGUE AARON");
static const u8 sSiMapName_LAYOUT_SI_LEAGUEBERTHA[] = _("LEAGUE BERTHA");
static const u8 sSiMapName_LAYOUT_SI_LEAGUEFLINT[] = _("LEAGUE FLINT");
static const u8 sSiMapName_LAYOUT_SI_LEAGUELUCIAN[] = _("LEAGUE LUCIAN");
static const u8 sSiMapName_LAYOUT_SI_LEAGUECYNTHIA[] = _("LEAGUE CYNTHIA");
const unsigned char *SiLayoutName(unsigned short layoutId) { switch(layoutId) {
case LAYOUT_SI_TWINLEAFTOWN: return sSiMapName_LAYOUT_SI_TWINLEAFTOWN;
case LAYOUT_SI_SANDGEMTOWN: return sSiMapName_LAYOUT_SI_SANDGEMTOWN;
case LAYOUT_SI_JUBILIFECITY: return sSiMapName_LAYOUT_SI_JUBILIFECITY;
case LAYOUT_SI_OREBURGHCITY: return sSiMapName_LAYOUT_SI_OREBURGHCITY;
case LAYOUT_SI_ROUTE201: return sSiMapName_LAYOUT_SI_ROUTE201;
case LAYOUT_SI_ROUTE202: return sSiMapName_LAYOUT_SI_ROUTE202;
case LAYOUT_SI_ROUTE203: return sSiMapName_LAYOUT_SI_ROUTE203;
case LAYOUT_SI_VERITYLAKEFRONT: return sSiMapName_LAYOUT_SI_VERITYLAKEFRONT;
case LAYOUT_SI_LAKEVERITY: return sSiMapName_LAYOUT_SI_LAKEVERITY;
case LAYOUT_SI_OREBURGHGATE_1F: return sSiMapName_LAYOUT_SI_OREBURGHGATE_1F;
case LAYOUT_SI_OREBURGHMINE_B1F: return sSiMapName_LAYOUT_SI_OREBURGHMINE_B1F;
case LAYOUT_SI_OREBURGHMINE_B2F: return sSiMapName_LAYOUT_SI_OREBURGHMINE_B2F;
case LAYOUT_SI_TWINLEAFTOWN_MAINHOUSE_1F: return sSiMapName_LAYOUT_SI_TWINLEAFTOWN_MAINHOUSE_1F;
case LAYOUT_SI_TWINLEAFTOWN_MAINHOUSE_2F: return sSiMapName_LAYOUT_SI_TWINLEAFTOWN_MAINHOUSE_2F;
case LAYOUT_SI_TWINLEAF_TOWN_RIVALSHOUSE_F1: return sSiMapName_LAYOUT_SI_TWINLEAF_TOWN_RIVALSHOUSE_F1;
case LAYOUT_SI_TWINLEAF_TOWN_RIVALSHOUSE_F2: return sSiMapName_LAYOUT_SI_TWINLEAF_TOWN_RIVALSHOUSE_F2;
case LAYOUT_SI_TWINLEAFTOWN_HAOUSE1: return sSiMapName_LAYOUT_SI_TWINLEAFTOWN_HAOUSE1;
case LAYOUT_SI_TWINLEAFTOWN_HOUSE2: return sSiMapName_LAYOUT_SI_TWINLEAFTOWN_HOUSE2;
case LAYOUT_SI_SANDGEMTOWN_RIVALHOUSE_F1: return sSiMapName_LAYOUT_SI_SANDGEMTOWN_RIVALHOUSE_F1;
case LAYOUT_SI_SANDGEMTOWN_RIVALHOUSE_F2: return sSiMapName_LAYOUT_SI_SANDGEMTOWN_RIVALHOUSE_F2;
case LAYOUT_SI_SANDGEMTOWN_HOUSE1: return sSiMapName_LAYOUT_SI_SANDGEMTOWN_HOUSE1;
case LAYOUT_SI_SANDGEMTOWN_POKEMONCENTER_1F: return sSiMapName_LAYOUT_SI_SANDGEMTOWN_POKEMONCENTER_1F;
case LAYOUT_SI_SANDGEMTOWN_POKEMONCENTER_2F: return sSiMapName_LAYOUT_SI_SANDGEMTOWN_POKEMONCENTER_2F;
case LAYOUT_SI_SANDGEMTOWN_MART: return sSiMapName_LAYOUT_SI_SANDGEMTOWN_MART;
case LAYOUT_SI_JUBILIFECITY_POKEMONSCHOOL: return sSiMapName_LAYOUT_SI_JUBILIFECITY_POKEMONSCHOOL;
case LAYOUT_SI_JUBILIFECITY_JUBILIFETV_F1: return sSiMapName_LAYOUT_SI_JUBILIFECITY_JUBILIFETV_F1;
case LAYOUT_SI_JUBILIFECITY_JUBILIFETV_F2: return sSiMapName_LAYOUT_SI_JUBILIFECITY_JUBILIFETV_F2;
case LAYOUT_SI_JUBILIFECITY_JUBILIFETV_F3: return sSiMapName_LAYOUT_SI_JUBILIFECITY_JUBILIFETV_F3;
case LAYOUT_SI_JUBILIFECITY_JUBILIFETV_F4: return sSiMapName_LAYOUT_SI_JUBILIFECITY_JUBILIFETV_F4;
case LAYOUT_SI_JUBILIFECITY_POKETCHCOMPANY_F1: return sSiMapName_LAYOUT_SI_JUBILIFECITY_POKETCHCOMPANY_F1;
case LAYOUT_SI_JUBILIFECITY_POKETCHCOMPANY_F2: return sSiMapName_LAYOUT_SI_JUBILIFECITY_POKETCHCOMPANY_F2;
case LAYOUT_SI_JUBILIFECITY_POKETCHCOMPANY_F3: return sSiMapName_LAYOUT_SI_JUBILIFECITY_POKETCHCOMPANY_F3;
case LAYOUT_SI_JUBILIFECITY_FLAT1_F1: return sSiMapName_LAYOUT_SI_JUBILIFECITY_FLAT1_F1;
case LAYOUT_SI_JUBILIFECITY_FLAT1_F2: return sSiMapName_LAYOUT_SI_JUBILIFECITY_FLAT1_F2;
case LAYOUT_SI_JUBILIFECITY_FLAT1_F3: return sSiMapName_LAYOUT_SI_JUBILIFECITY_FLAT1_F3;
case LAYOUT_SI_JUBILIFECITY_FLAT2_F1: return sSiMapName_LAYOUT_SI_JUBILIFECITY_FLAT2_F1;
case LAYOUT_SI_JUBILIFECITY_FLAT2_F2: return sSiMapName_LAYOUT_SI_JUBILIFECITY_FLAT2_F2;
case LAYOUT_SI_JUBILIFECITY_FLAT2_F3: return sSiMapName_LAYOUT_SI_JUBILIFECITY_FLAT2_F3;
case LAYOUT_SI_JUBILIFECITY_FLAT3_F1: return sSiMapName_LAYOUT_SI_JUBILIFECITY_FLAT3_F1;
case LAYOUT_SI_JUBILIFECITY_FLAT3_F2: return sSiMapName_LAYOUT_SI_JUBILIFECITY_FLAT3_F2;
case LAYOUT_SI_JUBILIFECITY_FLAT3_F3: return sSiMapName_LAYOUT_SI_JUBILIFECITY_FLAT3_F3;
case LAYOUT_SI_JUBILIFECITY_POKEMONCENTER_1F: return sSiMapName_LAYOUT_SI_JUBILIFECITY_POKEMONCENTER_1F;
case LAYOUT_SI_JUBILIFECITY_POKEMONCENTER_2F: return sSiMapName_LAYOUT_SI_JUBILIFECITY_POKEMONCENTER_2F;
case LAYOUT_SI_JUBILIFECITY_MART: return sSiMapName_LAYOUT_SI_JUBILIFECITY_MART;
case LAYOUT_SI_OREBURGHCITY_FLAT1_F1: return sSiMapName_LAYOUT_SI_OREBURGHCITY_FLAT1_F1;
case LAYOUT_SI_OREBURGHCITY_FLAT1_F2: return sSiMapName_LAYOUT_SI_OREBURGHCITY_FLAT1_F2;
case LAYOUT_SI_OREBURGHCITY_FLAT2_F1: return sSiMapName_LAYOUT_SI_OREBURGHCITY_FLAT2_F1;
case LAYOUT_SI_OREBURGHCITY_FLAT2_F2: return sSiMapName_LAYOUT_SI_OREBURGHCITY_FLAT2_F2;
case LAYOUT_SI_OREBURGHCITY_FLAT3_F1: return sSiMapName_LAYOUT_SI_OREBURGHCITY_FLAT3_F1;
case LAYOUT_SI_OREBURGHCITY_FLAT3_F2: return sSiMapName_LAYOUT_SI_OREBURGHCITY_FLAT3_F2;
case LAYOUT_SI_OREBURGHCITY_HOUSE1: return sSiMapName_LAYOUT_SI_OREBURGHCITY_HOUSE1;
case LAYOUT_SI_OREBURGHCITY_HOUSE2: return sSiMapName_LAYOUT_SI_OREBURGHCITY_HOUSE2;
case LAYOUT_SI_OREBURGHCITY_HOUSE3: return sSiMapName_LAYOUT_SI_OREBURGHCITY_HOUSE3;
case LAYOUT_SI_OREBURGHCITY_GYM: return sSiMapName_LAYOUT_SI_OREBURGHCITY_GYM;
case LAYOUT_SI_OREBURGHCITY_POKEMONCENTER_1F: return sSiMapName_LAYOUT_SI_OREBURGHCITY_POKEMONCENTER_1F;
case LAYOUT_SI_OREBURGHCITY_POKEMONCENTER_2F: return sSiMapName_LAYOUT_SI_OREBURGHCITY_POKEMONCENTER_2F;
case LAYOUT_SI_OREBURGHCITY_MART: return sSiMapName_LAYOUT_SI_OREBURGHCITY_MART;
case LAYOUT_SI_SANDGEMLAB: return sSiMapName_LAYOUT_SI_SANDGEMLAB;
case LAYOUT_SI_OREBURGHMUSEUM: return sSiMapName_LAYOUT_SI_OREBURGHMUSEUM;
case LAYOUT_SI_FLOAROMATOWN: return sSiMapName_LAYOUT_SI_FLOAROMATOWN;
case LAYOUT_SI_ETERNACITY: return sSiMapName_LAYOUT_SI_ETERNACITY;
case LAYOUT_SI_HEARTHOMECITY: return sSiMapName_LAYOUT_SI_HEARTHOMECITY;
case LAYOUT_SI_SOLACEONTOWN: return sSiMapName_LAYOUT_SI_SOLACEONTOWN;
case LAYOUT_SI_CELESTICTOWN: return sSiMapName_LAYOUT_SI_CELESTICTOWN;
case LAYOUT_SI_VEILSTONECITY: return sSiMapName_LAYOUT_SI_VEILSTONECITY;
case LAYOUT_SI_PASTORIACITY: return sSiMapName_LAYOUT_SI_PASTORIACITY;
case LAYOUT_SI_CANALAVECITY: return sSiMapName_LAYOUT_SI_CANALAVECITY;
case LAYOUT_SI_SNOWPOINTCITY: return sSiMapName_LAYOUT_SI_SNOWPOINTCITY;
case LAYOUT_SI_SUNYSHORECITY: return sSiMapName_LAYOUT_SI_SUNYSHORECITY;
case LAYOUT_SI_POKMONLEAGUE: return sSiMapName_LAYOUT_SI_POKMONLEAGUE;
case LAYOUT_SI_ROUTE204: return sSiMapName_LAYOUT_SI_ROUTE204;
case LAYOUT_SI_ROUTE205_NORTH: return sSiMapName_LAYOUT_SI_ROUTE205_NORTH;
case LAYOUT_SI_ROUTE205_SOUTH: return sSiMapName_LAYOUT_SI_ROUTE205_SOUTH;
case LAYOUT_SI_ROUTE206: return sSiMapName_LAYOUT_SI_ROUTE206;
case LAYOUT_SI_ROUTE207: return sSiMapName_LAYOUT_SI_ROUTE207;
case LAYOUT_SI_ROUTE208: return sSiMapName_LAYOUT_SI_ROUTE208;
case LAYOUT_SI_ROUTE209: return sSiMapName_LAYOUT_SI_ROUTE209;
case LAYOUT_SI_ROUTE210_NORTH: return sSiMapName_LAYOUT_SI_ROUTE210_NORTH;
case LAYOUT_SI_ROUTE210_SOUTH: return sSiMapName_LAYOUT_SI_ROUTE210_SOUTH;
case LAYOUT_SI_ROUTE211_EAST: return sSiMapName_LAYOUT_SI_ROUTE211_EAST;
case LAYOUT_SI_ROUTE211_WEST: return sSiMapName_LAYOUT_SI_ROUTE211_WEST;
case LAYOUT_SI_ROUTE212_NORTH: return sSiMapName_LAYOUT_SI_ROUTE212_NORTH;
case LAYOUT_SI_ROUTE212_SOUTH: return sSiMapName_LAYOUT_SI_ROUTE212_SOUTH;
case LAYOUT_SI_ROUTE213: return sSiMapName_LAYOUT_SI_ROUTE213;
case LAYOUT_SI_ROUTE214: return sSiMapName_LAYOUT_SI_ROUTE214;
case LAYOUT_SI_ROUTE215: return sSiMapName_LAYOUT_SI_ROUTE215;
case LAYOUT_SI_ROUTE216: return sSiMapName_LAYOUT_SI_ROUTE216;
case LAYOUT_SI_ROUTE217: return sSiMapName_LAYOUT_SI_ROUTE217;
case LAYOUT_SI_ROUTE218: return sSiMapName_LAYOUT_SI_ROUTE218;
case LAYOUT_SI_ROUTE219: return sSiMapName_LAYOUT_SI_ROUTE219;
case LAYOUT_SI_ROUTE220: return sSiMapName_LAYOUT_SI_ROUTE220;
case LAYOUT_SI_ROUTE221: return sSiMapName_LAYOUT_SI_ROUTE221;
case LAYOUT_SI_ROUTE222: return sSiMapName_LAYOUT_SI_ROUTE222;
case LAYOUT_SI_ROUTE223: return sSiMapName_LAYOUT_SI_ROUTE223;
case LAYOUT_SI_ROUTE224: return sSiMapName_LAYOUT_SI_ROUTE224;
case LAYOUT_SI_ROUTE225: return sSiMapName_LAYOUT_SI_ROUTE225;
case LAYOUT_SI_ROUTE226: return sSiMapName_LAYOUT_SI_ROUTE226;
case LAYOUT_SI_ROUTE227: return sSiMapName_LAYOUT_SI_ROUTE227;
case LAYOUT_SI_ROUTE228: return sSiMapName_LAYOUT_SI_ROUTE228;
case LAYOUT_SI_ROUTE229: return sSiMapName_LAYOUT_SI_ROUTE229;
case LAYOUT_SI_ROUTE230: return sSiMapName_LAYOUT_SI_ROUTE230;
case LAYOUT_SI_VALORLAKEFRONT: return sSiMapName_LAYOUT_SI_VALORLAKEFRONT;
case LAYOUT_SI_ACUITYLAKEFRONT: return sSiMapName_LAYOUT_SI_ACUITYLAKEFRONT;
case LAYOUT_SI_FIGHTAREA: return sSiMapName_LAYOUT_SI_FIGHTAREA;
case LAYOUT_SI_SURVIVALAREA: return sSiMapName_LAYOUT_SI_SURVIVALAREA;
case LAYOUT_SI_RESORTAREA: return sSiMapName_LAYOUT_SI_RESORTAREA;
case LAYOUT_SI_LAKEVALOR: return sSiMapName_LAYOUT_SI_LAKEVALOR;
case LAYOUT_SI_LAKEACUITY: return sSiMapName_LAYOUT_SI_LAKEACUITY;
case LAYOUT_SI_VALLEYWINDWORKS: return sSiMapName_LAYOUT_SI_VALLEYWINDWORKS;
case LAYOUT_SI_ETERNAFOREST: return sSiMapName_LAYOUT_SI_ETERNAFOREST;
case LAYOUT_SI_FLOAROMAMEADOW: return sSiMapName_LAYOUT_SI_FLOAROMAMEADOW;
case LAYOUT_SI_RAVAGEDPATH: return sSiMapName_LAYOUT_SI_RAVAGEDPATH;
case LAYOUT_SI_MTCORONET_B1F: return sSiMapName_LAYOUT_SI_MTCORONET_B1F;
case LAYOUT_SI_MTCORONET_1F_SOUTH: return sSiMapName_LAYOUT_SI_MTCORONET_1F_SOUTH;
case LAYOUT_SI_MTCORONET_1F_NORTH_ROOM1: return sSiMapName_LAYOUT_SI_MTCORONET_1F_NORTH_ROOM1;
case LAYOUT_SI_MTCORONET_1F_NORTH_ROOM2: return sSiMapName_LAYOUT_SI_MTCORONET_1F_NORTH_ROOM2;
case LAYOUT_SI_OLDCHATEAU_ENTRANCE: return sSiMapName_LAYOUT_SI_OLDCHATEAU_ENTRANCE;
case LAYOUT_SI_OLDCHATEAU_SIDEROOM_1: return sSiMapName_LAYOUT_SI_OLDCHATEAU_SIDEROOM_1;
case LAYOUT_SI_OLDCHATEAU_SIDEROOM_2: return sSiMapName_LAYOUT_SI_OLDCHATEAU_SIDEROOM_2;
case LAYOUT_SI_OLDCHATEAU_DININGROOM: return sSiMapName_LAYOUT_SI_OLDCHATEAU_DININGROOM;
case LAYOUT_SI_OLDCHATEAU_2F: return sSiMapName_LAYOUT_SI_OLDCHATEAU_2F;
case LAYOUT_SI_ROUTE206_NORTH: return sSiMapName_LAYOUT_SI_ROUTE206_NORTH;
case LAYOUT_SI_ROUTE206_SOUTH: return sSiMapName_LAYOUT_SI_ROUTE206_SOUTH;
case LAYOUT_SI_ROUTE208_ACCESS: return sSiMapName_LAYOUT_SI_ROUTE208_ACCESS;
case LAYOUT_SI_ROUTE209_ACCESS: return sSiMapName_LAYOUT_SI_ROUTE209_ACCESS;
case LAYOUT_SI_ROUTE212_ACCESS: return sSiMapName_LAYOUT_SI_ROUTE212_ACCESS;
case LAYOUT_SI_ROUTE213_ACCESS: return sSiMapName_LAYOUT_SI_ROUTE213_ACCESS;
case LAYOUT_SI_ROUTE214_ACCESS: return sSiMapName_LAYOUT_SI_ROUTE214_ACCESS;
case LAYOUT_SI_ROUTE215_ACCESS: return sSiMapName_LAYOUT_SI_ROUTE215_ACCESS;
case LAYOUT_SI_ROUTE218_EAST: return sSiMapName_LAYOUT_SI_ROUTE218_EAST;
case LAYOUT_SI_ROUTE218_WEST: return sSiMapName_LAYOUT_SI_ROUTE218_WEST;
case LAYOUT_SI_ROUTE222_ACCESS: return sSiMapName_LAYOUT_SI_ROUTE222_ACCESS;
case LAYOUT_SI_ROUTE225_ACCESS: return sSiMapName_LAYOUT_SI_ROUTE225_ACCESS;
case LAYOUT_SI_ROUTE226_ACCESS: return sSiMapName_LAYOUT_SI_ROUTE226_ACCESS;
case LAYOUT_SI_HOTELGRANDLAKE: return sSiMapName_LAYOUT_SI_HOTELGRANDLAKE;
case LAYOUT_SI_VALLEYWINDOWORKS_INDOOR: return sSiMapName_LAYOUT_SI_VALLEYWINDOWORKS_INDOOR;
case LAYOUT_SI_ROUTE205_HOUSE: return sSiMapName_LAYOUT_SI_ROUTE205_HOUSE;
case LAYOUT_SI_FLOAROMATOWN_HOUSE1: return sSiMapName_LAYOUT_SI_FLOAROMATOWN_HOUSE1;
case LAYOUT_SI_FLOAROMATOWN_HOUSE2: return sSiMapName_LAYOUT_SI_FLOAROMATOWN_HOUSE2;
case LAYOUT_SI_FLOAROMATOWN_FLOWERSHOP: return sSiMapName_LAYOUT_SI_FLOAROMATOWN_FLOWERSHOP;
case LAYOUT_SI_FLOAROMATOWN_POKEMONCENTER_1F: return sSiMapName_LAYOUT_SI_FLOAROMATOWN_POKEMONCENTER_1F;
case LAYOUT_SI_FLOAROMATWON_POKEMONCENTER_2F: return sSiMapName_LAYOUT_SI_FLOAROMATWON_POKEMONCENTER_2F;
case LAYOUT_SI_FLOAROMATOWN_MART: return sSiMapName_LAYOUT_SI_FLOAROMATOWN_MART;
case LAYOUT_SI_FLOAROMAMEADOW_HOUSE: return sSiMapName_LAYOUT_SI_FLOAROMAMEADOW_HOUSE;
case LAYOUT_SI_ETERNACITY_FLAT1_F1: return sSiMapName_LAYOUT_SI_ETERNACITY_FLAT1_F1;
case LAYOUT_SI_ETERNACITY_FLAT1_F2: return sSiMapName_LAYOUT_SI_ETERNACITY_FLAT1_F2;
case LAYOUT_SI_ETERNACITY_FLAT1_F3: return sSiMapName_LAYOUT_SI_ETERNACITY_FLAT1_F3;
case LAYOUT_SI_ETERNACITY_HERBSHOP: return sSiMapName_LAYOUT_SI_ETERNACITY_HERBSHOP;
case LAYOUT_SI_ETERNACITY_UNDERGROUNDMANHOUSE: return sSiMapName_LAYOUT_SI_ETERNACITY_UNDERGROUNDMANHOUSE;
case LAYOUT_SI_ETERNACITY_CYCLESHOP: return sSiMapName_LAYOUT_SI_ETERNACITY_CYCLESHOP;
case LAYOUT_SI_ETERNACITY_HOUSE1: return sSiMapName_LAYOUT_SI_ETERNACITY_HOUSE1;
case LAYOUT_SI_ETERNACITY_HOUSE2: return sSiMapName_LAYOUT_SI_ETERNACITY_HOUSE2;
case LAYOUT_SI_ETERNACITY_GYM: return sSiMapName_LAYOUT_SI_ETERNACITY_GYM;
case LAYOUT_SI_ETERNACITY_POKEMONCENTER_F1: return sSiMapName_LAYOUT_SI_ETERNACITY_POKEMONCENTER_F1;
case LAYOUT_SI_ETERNACITY_POKEMONCENTER_F2: return sSiMapName_LAYOUT_SI_ETERNACITY_POKEMONCENTER_F2;
case LAYOUT_SI_ETERNACITY_MART: return sSiMapName_LAYOUT_SI_ETERNACITY_MART;
case LAYOUT_SI_ETERNACITY_GALACTICBUILDING_1F: return sSiMapName_LAYOUT_SI_ETERNACITY_GALACTICBUILDING_1F;
case LAYOUT_SI_ETERNACITY_GALACTICBUILDING_2F: return sSiMapName_LAYOUT_SI_ETERNACITY_GALACTICBUILDING_2F;
case LAYOUT_SI_ETERNACITY_GALACTICBUILDING_3F: return sSiMapName_LAYOUT_SI_ETERNACITY_GALACTICBUILDING_3F;
case LAYOUT_SI_ETERNACITY_GALACTICBUILDING_4F: return sSiMapName_LAYOUT_SI_ETERNACITY_GALACTICBUILDING_4F;
case LAYOUT_SI_ETERNACITY_GALACTICBUILDING_B1F: return sSiMapName_LAYOUT_SI_ETERNACITY_GALACTICBUILDING_B1F;
case LAYOUT_SI_HEARTHOMECITY_POKEMONCENTER: return sSiMapName_LAYOUT_SI_HEARTHOMECITY_POKEMONCENTER;
case LAYOUT_SI_HEARTHOMECITY_MART: return sSiMapName_LAYOUT_SI_HEARTHOMECITY_MART;
case LAYOUT_SI_HEARTHOMECITY_HOUSE: return sSiMapName_LAYOUT_SI_HEARTHOMECITY_HOUSE;
case LAYOUT_SI_SOLACEONTOWN_POKEMONCENTER: return sSiMapName_LAYOUT_SI_SOLACEONTOWN_POKEMONCENTER;
case LAYOUT_SI_SOLACEONTOWN_MART: return sSiMapName_LAYOUT_SI_SOLACEONTOWN_MART;
case LAYOUT_SI_SOLACEONTOWN_HOUSE: return sSiMapName_LAYOUT_SI_SOLACEONTOWN_HOUSE;
case LAYOUT_SI_VEILSTONECITY_POKEMONCENTER: return sSiMapName_LAYOUT_SI_VEILSTONECITY_POKEMONCENTER;
case LAYOUT_SI_VEILSTONECITY_MART: return sSiMapName_LAYOUT_SI_VEILSTONECITY_MART;
case LAYOUT_SI_VEILSTONECITY_HOUSE: return sSiMapName_LAYOUT_SI_VEILSTONECITY_HOUSE;
case LAYOUT_SI_PASTORIACITY_POKEMONCENTER: return sSiMapName_LAYOUT_SI_PASTORIACITY_POKEMONCENTER;
case LAYOUT_SI_PASTORIACITY_MART: return sSiMapName_LAYOUT_SI_PASTORIACITY_MART;
case LAYOUT_SI_PASTORIACITY_HOUSE: return sSiMapName_LAYOUT_SI_PASTORIACITY_HOUSE;
case LAYOUT_SI_CELESTICTOWN_POKEMONCENTER: return sSiMapName_LAYOUT_SI_CELESTICTOWN_POKEMONCENTER;
case LAYOUT_SI_CELESTICTOWN_MART: return sSiMapName_LAYOUT_SI_CELESTICTOWN_MART;
case LAYOUT_SI_CELESTICTOWN_HOUSE: return sSiMapName_LAYOUT_SI_CELESTICTOWN_HOUSE;
case LAYOUT_SI_CANALAVECITY_POKEMONCENTER: return sSiMapName_LAYOUT_SI_CANALAVECITY_POKEMONCENTER;
case LAYOUT_SI_CANALAVECITY_MART: return sSiMapName_LAYOUT_SI_CANALAVECITY_MART;
case LAYOUT_SI_CANALAVECITY_HOUSE: return sSiMapName_LAYOUT_SI_CANALAVECITY_HOUSE;
case LAYOUT_SI_SNOWPOINTCITY_POKEMONCENTER: return sSiMapName_LAYOUT_SI_SNOWPOINTCITY_POKEMONCENTER;
case LAYOUT_SI_SNOWPOINTCITY_MART: return sSiMapName_LAYOUT_SI_SNOWPOINTCITY_MART;
case LAYOUT_SI_SNOWPOINTCITY_HOUSE: return sSiMapName_LAYOUT_SI_SNOWPOINTCITY_HOUSE;
case LAYOUT_SI_SUNYSHORECITY_POKEMONCENTER: return sSiMapName_LAYOUT_SI_SUNYSHORECITY_POKEMONCENTER;
case LAYOUT_SI_SUNYSHORECITY_MART: return sSiMapName_LAYOUT_SI_SUNYSHORECITY_MART;
case LAYOUT_SI_SUNYSHORECITY_HOUSE: return sSiMapName_LAYOUT_SI_SUNYSHORECITY_HOUSE;
case LAYOUT_SI_FIGHTAREA_POKEMONCENTER: return sSiMapName_LAYOUT_SI_FIGHTAREA_POKEMONCENTER;
case LAYOUT_SI_FIGHTAREA_MART: return sSiMapName_LAYOUT_SI_FIGHTAREA_MART;
case LAYOUT_SI_FIGHTAREA_HOUSE: return sSiMapName_LAYOUT_SI_FIGHTAREA_HOUSE;
case LAYOUT_SI_RESORTAREA_POKEMONCENTER: return sSiMapName_LAYOUT_SI_RESORTAREA_POKEMONCENTER;
case LAYOUT_SI_RESORTAREA_MART: return sSiMapName_LAYOUT_SI_RESORTAREA_MART;
case LAYOUT_SI_RESORTAREA_HOUSE: return sSiMapName_LAYOUT_SI_RESORTAREA_HOUSE;
case LAYOUT_SI_SURVIVALAREA_POKEMONCENTER: return sSiMapName_LAYOUT_SI_SURVIVALAREA_POKEMONCENTER;
case LAYOUT_SI_SURVIVALAREA_MART: return sSiMapName_LAYOUT_SI_SURVIVALAREA_MART;
case LAYOUT_SI_SURVIVALAREA_HOUSE: return sSiMapName_LAYOUT_SI_SURVIVALAREA_HOUSE;
case LAYOUT_SI_HEARTHOMECITY_GYM: return sSiMapName_LAYOUT_SI_HEARTHOMECITY_GYM;
case LAYOUT_SI_VEILSTONECITY_GYM: return sSiMapName_LAYOUT_SI_VEILSTONECITY_GYM;
case LAYOUT_SI_PASTORIACITY_GYM: return sSiMapName_LAYOUT_SI_PASTORIACITY_GYM;
case LAYOUT_SI_CANALAVECITY_GYM: return sSiMapName_LAYOUT_SI_CANALAVECITY_GYM;
case LAYOUT_SI_SNOWPOINTCITY_GYM: return sSiMapName_LAYOUT_SI_SNOWPOINTCITY_GYM;
case LAYOUT_SI_SUNYSHORECITY_GYM: return sSiMapName_LAYOUT_SI_SUNYSHORECITY_GYM;
case LAYOUT_SI_CANALAVELIBRARY: return sSiMapName_LAYOUT_SI_CANALAVELIBRARY;
case LAYOUT_SI_VEILSTONEHQ: return sSiMapName_LAYOUT_SI_VEILSTONEHQ;
case LAYOUT_SI_MTCORONETSUMMIT: return sSiMapName_LAYOUT_SI_MTCORONETSUMMIT;
case LAYOUT_SI_SPEARPILLAR: return sSiMapName_LAYOUT_SI_SPEARPILLAR;
case LAYOUT_SI_DISTORTIONWORLD: return sSiMapName_LAYOUT_SI_DISTORTIONWORLD;
case LAYOUT_SI_HALLOFORIGIN: return sSiMapName_LAYOUT_SI_HALLOFORIGIN;
case LAYOUT_SI_TURNBACKCAVE: return sSiMapName_LAYOUT_SI_TURNBACKCAVE;
case LAYOUT_SI_SNOWPOINTTEMPLE: return sSiMapName_LAYOUT_SI_SNOWPOINTTEMPLE;
case LAYOUT_SI_VICTORYROAD: return sSiMapName_LAYOUT_SI_VICTORYROAD;
case LAYOUT_SI_LEAGUEAARON: return sSiMapName_LAYOUT_SI_LEAGUEAARON;
case LAYOUT_SI_LEAGUEBERTHA: return sSiMapName_LAYOUT_SI_LEAGUEBERTHA;
case LAYOUT_SI_LEAGUEFLINT: return sSiMapName_LAYOUT_SI_LEAGUEFLINT;
case LAYOUT_SI_LEAGUELUCIAN: return sSiMapName_LAYOUT_SI_LEAGUELUCIAN;
case LAYOUT_SI_LEAGUECYNTHIA: return sSiMapName_LAYOUT_SI_LEAGUECYNTHIA;
default: return NULL; }}

void SiSetHealPoint(void) {
 gSaveBlock1Ptr->lastHealLocation = gSaveBlock1Ptr->location;
 gSaveBlock1Ptr->lastHealLocation.warpId = WARP_ID_NONE;
 gSaveBlock1Ptr->lastHealLocation.x = gSaveBlock1Ptr->pos.x;
 gSaveBlock1Ptr->lastHealLocation.y = gSaveBlock1Ptr->pos.y;
}

#include "item.h"
#include "pokemon.h"
#include "constants/items.h"
void SiCoachFillCandy(void)
{
    u32 count;
    gSpecialVar_Result = FALSE;
    if (!SiIsSeason() || !FlagGet(FLAG_HE_ANTI_GRINDING)) return;
    count = CountTotalItemQuantityInBag(ITEM_RARE_CANDY);
    gSpecialVar_Result = count >= 999 || AddBagItem(ITEM_RARE_CANDY, 999 - count);
}
void SiCoachMaxIvs(void)
{
    u32 i, j;
    u8 value = 31;
    if (!SiIsSeason() || !FlagGet(FLAG_HE_ANTI_GRINDING)) return;
    for (i = 0; i < PARTY_SIZE; i++)
    {
        if (!GetMonData(&gPlayerParty[i], MON_DATA_SPECIES) || GetMonData(&gPlayerParty[i], MON_DATA_IS_EGG)) continue;
        for (j = 0; j < 6; j++) SetMonData(&gPlayerParty[i], MON_DATA_HP_IV + j, &value);
        CalculateMonStats(&gPlayerParty[i]);
    }
}

static bool8 SiHasPartner(u16 species)
{
    u32 i;
    for(i=0;i<PARTY_SIZE;i++)
        if(GetMonData(&gPlayerParty[i],MON_DATA_SPECIES)==species&&!GetMonData(&gPlayerParty[i],MON_DATA_IS_EGG))
            return TRUE;
    return FALSE;
}
void SiCheckBudew(void) {gSpecialVar_Result=SiHasPartner(SPECIES_BUDEW);}
void SiCheckStarly(void) {gSpecialVar_Result=SiHasPartner(SPECIES_STARLY);}
void SiInferStarter(void)
{
    u32 i,species;
    if(VarGet(VAR_SI_STARTER)>=1&&VarGet(VAR_SI_STARTER)<=3)return;
    for(i=0;i<PARTY_SIZE;i++)
    {
        species=GetMonData(&gPlayerParty[i],MON_DATA_SPECIES);
        if(species==SPECIES_TURTWIG||species==SPECIES_GROTLE||species==SPECIES_TORTERRA){VarSet(VAR_SI_STARTER,1);return;}
        if(species==SPECIES_CHIMCHAR||species==SPECIES_MONFERNO||species==SPECIES_INFERNAPE){VarSet(VAR_SI_STARTER,2);return;}
        if(species==SPECIES_PIPLUP||species==SPECIES_PRINPLUP||species==SPECIES_EMPOLEON){VarSet(VAR_SI_STARTER,3);return;}
    }
    VarSet(VAR_SI_STARTER,1);
}
