// Generated by tools/localization/generate_story.py.

extern const u8 HE_English_0[];
extern const u8 HE_CoachGift[];
extern const u8 HE_English_1[];
extern const u8 HE_CoachEnough[];
extern const u8 HE_English_2[];
extern const u8 HE_CoachOff[];
extern const u8 HE_English_3[];
extern const u8 HE_CoachBagFullText[];
extern const u8 HE_English_4[];
extern const u8 HE_QuestBoardIntro[];
extern const u8 HE_English_5[];
extern const u8 HE_QuestTarget[];
extern const u8 HE_English_6[];
extern const u8 HE_QuestReplace[];
extern const u8 HE_English_7[];
extern const u8 HE_QuestAccepted[];
extern const u8 HE_English_8[];
extern const u8 HE_QuestNoActive[];
extern const u8 HE_English_9[];
extern const u8 HE_QuestEarlyText[];
extern const u8 HE_English_10[];
extern const u8 HE_QuestFinishedRegion[];
extern const u8 HE_English_11[];
extern const u8 HE_QuestResearchIntro[];
extern const u8 HE_English_12[];
extern const u8 HE_QuestNeedEvidence[];
extern const u8 HE_English_13[];
extern const u8 HE_QuestResearchReady[];
extern const u8 HE_English_14[];
extern const u8 HE_QuestResearchNight[];
extern const u8 HE_English_15[];
extern const u8 HE_QuestBeaconIntro[];
extern const u8 HE_English_16[];
extern const u8 HE_QuestNeedResearch[];
extern const u8 HE_English_17[];
extern const u8 HE_QuestNeedNight[];
extern const u8 HE_English_18[];
extern const u8 HE_QuestSignal[];
extern const u8 HE_English_19[];
extern const u8 HE_QuestRetry[];
extern const u8 HE_English_20[];
extern const u8 HE_QuestCapturedText[];
extern const u8 HE_English_21[];
extern const u8 HE_RainbowRingBagFullText[];
extern const u8 HE_English_22[];
extern const u8 HE_RainbowRecoverRingText[];
extern const u8 HE_English_23[];
extern const u8 HE_RainbowEarlyText[];
extern const u8 HE_English_24[];
extern const u8 HE_RainbowDistress[];
extern const u8 HE_English_25[];
extern const u8 HE_RainbowBriefing[];
extern const u8 HE_English_26[];
extern const u8 HE_RainbowMeteorHint[];
extern const u8 HE_English_27[];
extern const u8 HE_RainbowSpaceHint[];
extern const u8 HE_English_28[];
extern const u8 HE_RainbowShipHint[];
extern const u8 HE_English_29[];
extern const u8 HE_RainbowSkyHint[];
extern const u8 HE_English_30[];
extern const u8 HE_RainbowScoutIntro[];
extern const u8 HE_English_31[];
extern const u8 HE_RainbowDefeat[];
extern const u8 HE_English_32[];
extern const u8 HE_RainbowScoutAfter[];
extern const u8 HE_English_33[];
extern const u8 HE_RainbowVesperIntro[];
extern const u8 HE_English_34[];
extern const u8 HE_RainbowVesperAfter[];
extern const u8 HE_English_35[];
extern const u8 HE_RainbowShipIntro[];
extern const u8 HE_English_36[];
extern const u8 HE_RainbowShipAfter[];
extern const u8 HE_English_37[];
extern const u8 HE_RainbowGiovanniIntro[];
extern const u8 HE_English_38[];
extern const u8 HE_RainbowGiovanniAfter[];
extern const u8 HE_English_39[];
extern const u8 HE_RainbowRayChoice[];
extern const u8 HE_English_40[];
extern const u8 HE_RainbowEnding[];
extern const u8 HE_English_41[];
extern const u8 HE_RainbowRestored[];
extern const u8 HE_English_42[];
extern const u8 HE_RainbowWaitText[];
extern const u8 HE_English_43[];
extern const u8 HE_BugMiloIntro[];
extern const u8 HE_English_44[];
extern const u8 HE_BugMiloDefeat[];
extern const u8 HE_English_45[];
extern const u8 HE_BugMiloAfter[];
extern const u8 HE_English_46[];
extern const u8 HE_BugLiaIntro[];
extern const u8 HE_English_47[];
extern const u8 HE_BugLiaDefeat[];
extern const u8 HE_English_48[];
extern const u8 HE_BugLiaAfter[];
extern const u8 HE_English_49[];
extern const u8 HE_PostJournalStartText[];
extern const u8 HE_English_50[];
extern const u8 HE_Thermal_Intro[];
extern const u8 HE_English_51[];
extern const u8 HE_Thermal_After[];
extern const u8 HE_English_52[];
extern const u8 HE_Thermal_Done[];
extern const u8 HE_English_53[];
extern const u8 HE_Thermal_Pattern[];
extern const u8 HE_English_54[];
extern const u8 HE_ArrivalThermal_Text[];
extern const u8 HE_English_55[];
extern const u8 HE_NeedThermal_Text[];
extern const u8 HE_English_56[];
extern const u8 HE_Supply_Intro[];
extern const u8 HE_English_57[];
extern const u8 HE_Supply_After[];
extern const u8 HE_English_58[];
extern const u8 HE_Supply_Done[];
extern const u8 HE_English_59[];
extern const u8 HE_Supply_Pattern[];
extern const u8 HE_English_60[];
extern const u8 HE_ArrivalSupply_Text[];
extern const u8 HE_English_61[];
extern const u8 HE_NeedSupply_Text[];
extern const u8 HE_English_62[];
extern const u8 HE_Forest_Intro[];
extern const u8 HE_English_63[];
extern const u8 HE_Forest_After[];
extern const u8 HE_English_64[];
extern const u8 HE_Forest_Done[];
extern const u8 HE_English_65[];
extern const u8 HE_Forest_Pattern[];
extern const u8 HE_English_66[];
extern const u8 HE_ArrivalForest_Text[];
extern const u8 HE_English_67[];
extern const u8 HE_NeedForest_Text[];
extern const u8 HE_English_68[];
extern const u8 HE_Orbit_Intro[];
extern const u8 HE_English_69[];
extern const u8 HE_Orbit_After[];
extern const u8 HE_English_70[];
extern const u8 HE_Orbit_Done[];
extern const u8 HE_English_71[];
extern const u8 HE_Orbit_Pattern[];
extern const u8 HE_English_72[];
extern const u8 HE_ArrivalOrbit_Text[];
extern const u8 HE_English_73[];
extern const u8 HE_NeedOrbit_Text[];
extern const u8 HE_English_74[];
extern const u8 HE_Ocean_Intro[];
extern const u8 HE_English_75[];
extern const u8 HE_Ocean_After[];
extern const u8 HE_English_76[];
extern const u8 HE_Ocean_Done[];
extern const u8 HE_English_77[];
extern const u8 HE_Ocean_Pattern[];
extern const u8 HE_English_78[];
extern const u8 HE_ArrivalOcean_Text[];
extern const u8 HE_English_79[];
extern const u8 HE_NeedOcean_Text[];
extern const u8 HE_English_80[];
extern const u8 HE_RescueReport[];
extern const u8 HE_English_81[];
extern const u8 HE_EnergyReport[];
extern const u8 HE_English_82[];
extern const u8 HE_RelayDoneReport[];
extern const u8 HE_English_83[];
extern const u8 HE_TooEarlyReport[];
extern const u8 HE_English_84[];
extern const u8 HE_LiaisonText[];
extern const u8 HE_English_85[];
extern const u8 HE_CampaignNextPulse[];
extern const u8 HE_English_86[];
extern const u8 HE_CampaignEnemyDefeat[];
extern const u8 HE_English_87[];
extern const u8 HE_GiovanniIntro[];
extern const u8 HE_English_88[];
extern const u8 HE_GiovanniDefeat[];
extern const u8 HE_English_89[];
extern const u8 HE_FinalCentralReport[];
extern const u8 HE_English_90[];
extern const u8 HE_FinalCentralNeeded[];
extern const u8 HE_English_91[];
extern const u8 HE_EpilogueText[];
extern const u8 HE_English_92[];
extern const u8 HE_CampaignGoalText0[];
extern const u8 HE_English_93[];
extern const u8 HE_CampaignGoalText1[];
extern const u8 HE_English_94[];
extern const u8 HE_CampaignGoalText2[];
extern const u8 HE_English_95[];
extern const u8 HE_CampaignGoalText3[];
extern const u8 HE_English_96[];
extern const u8 HE_CampaignGoalText4[];
extern const u8 HE_English_97[];
extern const u8 HE_CampaignGoalPeekoText[];
extern const u8 HE_English_98[];
extern const u8 HE_CampaignGoalDevonText[];
extern const u8 HE_English_99[];
extern const u8 HE_CampaignGoalText5[];
extern const u8 HE_English_100[];
extern const u8 HE_CampaignGoalText6[];
extern const u8 HE_English_101[];
extern const u8 HE_CampaignGoalText7[];
extern const u8 HE_English_102[];
extern const u8 HE_CampaignGoalText8[];
extern const u8 HE_English_103[];
extern const u8 HE_CampaignGoalText9[];
extern const u8 HE_English_104[];
extern const u8 HE_CampaignGoalText10[];
extern const u8 HE_English_105[];
extern const u8 HE_CampaignGoalText11[];
extern const u8 HE_English_106[];
extern const u8 HE_CampaignGoalText12[];
extern const u8 HE_English_107[];
extern const u8 HE_CampaignGoalText13[];
extern const u8 HE_English_108[];
extern const u8 HE_CampaignGoalText14[];
extern const u8 HE_English_109[];
extern const u8 HE_CampaignGoalText15[];
extern const u8 HE_English_110[];
extern const u8 HE_CampaignGoalText16[];
extern const u8 HE_English_111[];
extern const u8 HE_CampaignGoalText17[];
extern const u8 HE_English_112[];
extern const u8 HE_CampaignGoalText18[];
extern const u8 HE_English_113[];
extern const u8 HE_CampaignGoalText19[];
extern const u8 HE_English_114[];
extern const u8 HE_CampaignGoalText20[];
extern const u8 HE_English_115[];
extern const u8 HE_CampaignDoneText[];
extern const u8 HE_English_116[];
extern const u8 HE_Text_Journal[];
extern const u8 HE_English_117[];
extern const u8 HE_Text_GoalRustboro[];
extern const u8 HE_English_118[];
extern const u8 HE_Text_GoalDewford[];
extern const u8 HE_English_119[];
extern const u8 HE_Text_GoalBrawly[];
extern const u8 HE_English_120[];
extern const u8 HE_Text_GoalHarbor[];
extern const u8 HE_English_121[];
extern const u8 HE_Text_GoalMauville[];
extern const u8 HE_English_122[];
extern const u8 HE_Text_GoalWattson[];
extern const u8 HE_English_123[];
extern const u8 HE_Text_GoalEnd[];
extern const u8 HE_English_124[];
extern const u8 HE_Text_Decoder[];
extern const u8 HE_English_125[];
extern const u8 HE_Text_DecoderHow[];
extern const u8 HE_English_126[];
extern const u8 HE_Text_Early[];
extern const u8 HE_English_127[];
extern const u8 HE_Text_Medic[];
extern const u8 HE_English_128[];
extern const u8 HE_Text_Healed[];
extern const u8 HE_English_129[];
extern const u8 HE_Text_PuzzleWrong[];
extern const u8 HE_English_130[];
extern const u8 HE_Text_PuzzleDone[];
extern const u8 HE_English_131[];
extern const u8 HE_Text_NoDecoder[];
extern const u8 HE_English_132[];
extern const u8 HE_Text_NextPulse[];
extern const u8 HE_English_133[];
extern const u8 HE_Text_PatternRustboro[];
extern const u8 HE_English_134[];
extern const u8 HE_Text_RelayRustboroOff[];
extern const u8 HE_English_135[];
extern const u8 HE_Text_PatternDewford[];
extern const u8 HE_English_136[];
extern const u8 HE_Text_RelayDewfordOff[];
extern const u8 HE_English_137[];
extern const u8 HE_Text_PatternMauville[];
extern const u8 HE_English_138[];
extern const u8 HE_Text_RelayMauvilleOff[];
extern const u8 HE_English_139[];
extern const u8 HE_Text_CaveGuard[];
extern const u8 HE_English_140[];
extern const u8 HE_Text_CaveGuardLose[];
extern const u8 HE_English_141[];
extern const u8 HE_Text_GeneratorVesper[];
extern const u8 HE_English_142[];
extern const u8 HE_Text_GeneratorLose[];
extern const u8 HE_English_143[];
extern const u8 HE_Text_NeedHarbor[];
extern const u8 HE_English_144[];
extern const u8 HeRebuild_Text_Officer[];
extern const u8 HE_English_145[];
extern const u8 MossdeepCity_SpaceCenter_2F_Text_WhyWouldMagmaStealRocketFuel[];
extern const u8 HE_English_146[];
extern const u8 MossdeepCity_SpaceCenter_2F_Text_MagmaCantGetAwayWithThis[];
extern const u8 HE_English_147[];
extern const u8 MossdeepCity_SpaceCenter_2F_Text_YoureOutnumberedTakeUsOn[];
extern const u8 HE_English_148[];
extern const u8 MossdeepCity_SpaceCenter_2F_Text_GoodAnswer[];
extern const u8 HE_English_149[];
extern const u8 MossdeepCity_SpaceCenter_2F_Text_Grunt5Intro[];
extern const u8 MossdeepCity_SpaceCenter_2F_Text_Grunt6Intro[];
extern const u8 MossdeepCity_SpaceCenter_2F_Text_Grunt7Intro[];
extern const u8 MtChimney_Text_TabithaIntro[];
extern const u8 MtChimney_Text_Grunt2Intro[];
extern const u8 MtChimney_Text_Grunt1Intro[];
extern const u8 MagmaHideout_4F_Text_Grunt11Intro[];
extern const u8 MagmaHideout_4F_Text_Grunt12Intro[];
extern const u8 MagmaHideout_4F_Text_Grunt13Intro[];
extern const u8 MagmaHideout_4F_Text_TabithaIntro[];
extern const u8 Route119_WeatherInstitute_2F_Text_Grunt2Intro[];
extern const u8 Route119_WeatherInstitute_2F_Text_Grunt3Intro[];
extern const u8 Route119_WeatherInstitute_2F_Text_Grunt5Intro[];
extern const u8 HE_English_150[];
extern const u8 MossdeepCity_SpaceCenter_2F_Text_Grunt5Defeat[];
extern const u8 MossdeepCity_SpaceCenter_2F_Text_Grunt6Defeat[];
extern const u8 MossdeepCity_SpaceCenter_2F_Text_Grunt7Defeat[];
extern const u8 MossdeepCity_SpaceCenter_Text_TabithaDefeat[];
extern const u8 MtChimney_Text_TabithaDefeat[];
extern const u8 MtChimney_Text_Grunt2Defeat[];
extern const u8 MtChimney_Text_Grunt1Defeat[];
extern const u8 MagmaHideout_4F_Text_Grunt11Defeat[];
extern const u8 MagmaHideout_4F_Text_Grunt12Defeat[];
extern const u8 MagmaHideout_4F_Text_Grunt13Defeat[];
extern const u8 MagmaHideout_4F_Text_TabithaDefeat[];
extern const u8 Route119_WeatherInstitute_2F_Text_Grunt2Defeat[];
extern const u8 Route119_WeatherInstitute_2F_Text_Grunt3Defeat[];
extern const u8 Route119_WeatherInstitute_2F_Text_Grunt5Defeat[];
extern const u8 HE_English_151[];
extern const u8 MossdeepCity_SpaceCenter_2F_Text_Grunt6PostBattle[];
extern const u8 MossdeepCity_SpaceCenter_2F_Text_Grunt7PostBattle[];
extern const u8 MossdeepCity_SpaceCenter_2F_Text_Grunt5PostBattle[];
extern const u8 MtChimney_Text_TabithaPostBattle[];
extern const u8 MtChimney_Text_Grunt2PostBattle[];
extern const u8 MtChimney_Text_Grunt1PostBattle[];
extern const u8 MagmaHideout_4F_Text_Grunt11PostBattle[];
extern const u8 MagmaHideout_4F_Text_Grunt12PostBattle[];
extern const u8 MagmaHideout_4F_Text_Grunt13PostBattle[];
extern const u8 MagmaHideout_4F_Text_TabithaPostBattle[];
extern const u8 Route119_WeatherInstitute_2F_Text_Grunt2PostBattle[];
extern const u8 Route119_WeatherInstitute_2F_Text_Grunt3PostBattle[];
extern const u8 Route119_WeatherInstitute_2F_Text_Grunt5PostBattle[];
extern const u8 HE_English_152[];
extern const u8 MossdeepCity_SpaceCenter_2F_Text_WellTakeCareOfYou[];
extern const u8 HE_English_153[];
extern const u8 MossdeepCity_SpaceCenter_2F_Text_MaxieDontInterfere[];
extern const u8 HE_English_154[];
extern const u8 MossdeepCity_SpaceCenter_2F_Text_StevenWhyStealRocketFuel[];
extern const u8 HE_English_155[];
extern const u8 MossdeepCity_SpaceCenter_2F_Text_MaxieUseFuelToEruptVolcano[];
extern const u8 HE_English_156[];
extern const u8 MossdeepCity_SpaceCenter_2F_Text_StevenAreYouReadyToBattle[];
extern const u8 HE_English_157[];
extern const u8 MossdeepCity_SpaceCenter_2F_Text_StevenHurryGetReadyQuickly[];
extern const u8 HE_English_158[];
extern const u8 MossdeepCity_SpaceCenter_2F_Text_MaxieWeFailedIsAquaAlsoMisguided[];
extern const u8 HE_English_159[];
extern const u8 MossdeepCity_SpaceCenter_2F_Text_MaxieWeWillGiveUp[];
extern const u8 HE_English_160[];
extern const u8 MossdeepCity_SpaceCenter_2F_Text_StevenThankYouComeSeeMeAtHome[];
extern const u8 HE_English_161[];
extern const u8 MtChimney_Text_MaxieIntro[];
extern const u8 HE_English_162[];
extern const u8 MtChimney_Text_MaxieDefeat[];
extern const u8 HE_English_163[];
extern const u8 MtChimney_Text_MaxieYouHaventSeenLastOfMagma[];
extern const u8 HE_English_164[];
extern const u8 MtChimney_Text_ArchieGoStopTeamMagma[];
extern const u8 HE_English_165[];
extern const u8 MtChimney_Text_ArchieIHaveMyHandsFull[];
extern const u8 HE_English_166[];
extern const u8 MtChimney_Text_ArchieThankYou[];
extern const u8 HE_English_167[];
extern const u8 MtChimney_Text_MeteoriteFittedOnMachine[];
extern const u8 HE_English_168[];
extern const u8 MtChimney_Text_MachineMakesNoResponse[];
extern const u8 HE_English_169[];
extern const u8 SootopolisCity_Text_CitySign[];
extern const u8 HE_English_170[];
extern const u8 SootopolisCity_Text_WhereDidLegendariesGo[];
extern const u8 HE_English_171[];
extern const u8 SootopolisCity_Text_GroudonPleaseStop[];
extern const u8 HE_English_172[];
extern const u8 SootopolisCity_Text_AfterAllOurScheming[];
extern const u8 HE_English_173[];
extern const u8 SootopolisCity_Text_TryingMeaninglessToPokemon[];
extern const u8 HE_English_174[];
extern const u8 SootopolisCity_Text_InvolvedWithCrisisComeWithMe[];
extern const u8 HE_English_175[];
extern const u8 SootopolisCity_Text_DoesThisMakeYourFearPokemon[];
extern const u8 HE_English_176[];
extern const u8 SootopolisCity_Text_HereWereAreHelpWallace[];
extern const u8 HE_English_177[];
extern const u8 SootopolisCity_Text_KnowWhatsNeededToHelpHim[];
extern const u8 HE_English_178[];
extern const u8 SootopolisCity_Text_NeverBeenToSkyPillar[];
extern const u8 HE_English_179[];
extern const u8 SootopolisCity_Text_SoThatsRayquaza[];
extern const u8 HE_English_180[];
extern const u8 SootopolisCity_Text_MaxieArchieLeft[];
extern const u8 HE_English_181[];
extern const u8 SootopolisCity_Text_AquaMagmaDidntMeanHarm[];
extern const u8 HE_English_182[];
extern const u8 SootopolisCity_Text_ThankYouForHelpAcceptThis[];
extern const u8 HE_English_183[];
extern const u8 SootopolisCity_Text_ExplainWaterfallGoToGym[];
extern const u8 HE_English_184[];
extern const u8 MauvilleCity_Gym_Text_GymGuideAdvice[];
extern const u8 HE_English_185[];
extern const u8 MauvilleCity_Gym_Text_GymGuidePostVictory[];
extern const u8 HE_English_186[];
extern const u8 MauvilleCity_Gym_Text_KirkIntro[];
extern const u8 MauvilleCity_Gym_Text_ShawnIntro[];
extern const u8 MauvilleCity_Gym_Text_BenIntro[];
extern const u8 MauvilleCity_Gym_Text_VivianIntro[];
extern const u8 MauvilleCity_Gym_Text_AngeloIntro[];
extern const u8 DewfordTown_Gym_Text_TakaoIntro[];
extern const u8 DewfordTown_Gym_Text_JocelynIntro[];
extern const u8 DewfordTown_Gym_Text_LauraIntro[];
extern const u8 DewfordTown_Gym_Text_LilithIntro[];
extern const u8 DewfordTown_Gym_Text_BrendenIntro[];
extern const u8 DewfordTown_Gym_Text_CristianIntro[];
extern const u8 HE_English_187[];
extern const u8 MauvilleCity_Gym_Text_KirkDefeat[];
extern const u8 MauvilleCity_Gym_Text_ShawnDefeat[];
extern const u8 MauvilleCity_Gym_Text_BenDefeat[];
extern const u8 MauvilleCity_Gym_Text_VivianDefeat[];
extern const u8 MauvilleCity_Gym_Text_AngeloDefeat[];
extern const u8 DewfordTown_Gym_Text_TakaoDefeat[];
extern const u8 DewfordTown_Gym_Text_JocelynDefeat[];
extern const u8 DewfordTown_Gym_Text_LauraDefeat[];
extern const u8 DewfordTown_Gym_Text_LilithDefeat[];
extern const u8 DewfordTown_Gym_Text_BrendenDefeat[];
extern const u8 DewfordTown_Gym_Text_CristianDefeat[];
extern const u8 HE_English_188[];
extern const u8 MauvilleCity_Gym_Text_KirkPostBattle[];
extern const u8 MauvilleCity_Gym_Text_ShawnPostBattle[];
extern const u8 MauvilleCity_Gym_Text_BenPostBattle[];
extern const u8 MauvilleCity_Gym_Text_VivianPostBattle[];
extern const u8 MauvilleCity_Gym_Text_AngeloPostBattle[];
extern const u8 DewfordTown_Gym_Text_TakaoPostBattle[];
extern const u8 DewfordTown_Gym_Text_JocelynPostBattle[];
extern const u8 DewfordTown_Gym_Text_LauraPostBattle[];
extern const u8 DewfordTown_Gym_Text_LilithPostBattle[];
extern const u8 DewfordTown_Gym_Text_BrendenPostBattle[];
extern const u8 DewfordTown_Gym_Text_CristianPostBattle[];
extern const u8 HE_English_189[];
extern const u8 MauvilleCity_Gym_Text_WattsonIntro[];
extern const u8 HE_English_190[];
extern const u8 MauvilleCity_Gym_Text_WattsonDefeat[];
extern const u8 HE_English_191[];
extern const u8 MauvilleCity_Gym_Text_ReceivedDynamoBadge[];
extern const u8 HE_English_192[];
extern const u8 MauvilleCity_Gym_Text_ExplainDynamoBadgeTakeThis[];
extern const u8 HE_English_193[];
extern const u8 MauvilleCity_Gym_Text_ExplainShockWave[];
extern const u8 HE_English_194[];
extern const u8 MauvilleCity_Gym_Text_WattsonPostBattle[];
extern const u8 HE_English_195[];
extern const u8 MauvilleCity_Gym_Text_WattsonGoForthAndEndeavor[];
extern const u8 HE_English_196[];
extern const u8 HE_Text_WattsonNeedSignal[];
extern const u8 HE_English_197[];
extern const u8 HE_Text_Act3Radio[];
extern const u8 HE_English_198[];
extern const u8 HE_Text_Act3Wattson[];
extern const u8 HE_English_199[];
extern const u8 HE_Text_Act3End[];
extern const u8 HE_English_200[];
extern const u8 RivalsHouse_1F_Text_OhYoureTheNewNeighbor[];
extern const u8 HE_English_201[];
extern const u8 RivalsHouse_1F_Text_TooBusyToNoticeVisit[];
extern const u8 HE_English_202[];
extern const u8 RivalsHouse_1F_Text_MayWhoAreYou[];
extern const u8 RivalsHouse_2F_Text_MayWhoAreYou[];
extern const u8 HE_English_203[];
extern const u8 RivalsHouse_1F_Text_BrendanWhoAreYou[];
extern const u8 RivalsHouse_2F_Text_BrendanWhoAreYou[];
extern const u8 HE_English_204[];
extern const u8 RivalsHouse_1F_Text_DoYouHavePokemon[];
extern const u8 HE_English_205[];
extern const u8 AquaHideout_B1F_Text_Grunt2Intro[];
extern const u8 AquaHideout_B1F_Text_Grunt3Intro[];
extern const u8 AquaHideout_B1F_Text_Grunt5Intro[];
extern const u8 AquaHideout_B1F_Text_Grunt7Intro[];
extern const u8 AquaHideout_B2F_Text_Grunt4Intro[];
extern const u8 AquaHideout_B2F_Text_Grunt6Intro[];
extern const u8 AquaHideout_B2F_Text_Grunt8Intro[];
extern const u8 HE_English_206[];
extern const u8 AquaHideout_B1F_Text_Grunt2Defeat[];
extern const u8 AquaHideout_B1F_Text_Grunt3Defeat[];
extern const u8 AquaHideout_B1F_Text_Grunt5Defeat[];
extern const u8 AquaHideout_B1F_Text_Grunt7Defeat[];
extern const u8 AquaHideout_B2F_Text_Grunt4Defeat[];
extern const u8 AquaHideout_B2F_Text_Grunt6Defeat[];
extern const u8 AquaHideout_B2F_Text_Grunt8Defeat[];
extern const u8 HE_English_207[];
extern const u8 AquaHideout_B1F_Text_Grunt2PostBattle[];
extern const u8 AquaHideout_B1F_Text_Grunt3PostBattle[];
extern const u8 AquaHideout_B1F_Text_Grunt5PostBattle[];
extern const u8 AquaHideout_B1F_Text_Grunt7PostBattle[];
extern const u8 AquaHideout_B2F_Text_Grunt4PostBattle[];
extern const u8 AquaHideout_B2F_Text_Grunt6PostBattle[];
extern const u8 AquaHideout_B2F_Text_Grunt8PostBattle[];
extern const u8 HE_English_208[];
extern const u8 MauvilleCity_Text_UncleYourePushingIt[];
extern const u8 HE_English_209[];
extern const u8 MauvilleCity_Text_WallyWillYouBattleMe[];
extern const u8 HE_English_210[];
extern const u8 MauvilleCity_Text_WallyMyUncleWontKnowImStrong[];
extern const u8 HE_English_211[];
extern const u8 MauvilleCity_Text_WallyHereICome[];
extern const u8 HE_English_212[];
extern const u8 MauvilleCity_Text_WallyDefeat[];
extern const u8 HE_English_213[];
extern const u8 MauvilleCity_Text_WallyIllGoBackToVerdanturf[];
extern const u8 HE_English_214[];
extern const u8 MauvilleCity_Text_ThankYouNotEnoughToBattle[];
extern const u8 HE_English_215[];
extern const u8 MauvilleCity_Text_UncleNoNeedToBeDown[];
extern const u8 HE_English_216[];
extern const u8 MauvilleCity_Text_WallyPokenavCall[];
extern const u8 HE_English_217[];
extern const u8 MauvilleCity_Text_ScottYouDidntHoldBack[];
extern const u8 HE_English_218[];
extern const u8 HE_Text_MauvilleArrival[];
extern const u8 HE_English_219[];
extern const u8 EverGrandeCity_ChampionsRoom_Text_IntroSpeech[];
extern const u8 HE_English_220[];
extern const u8 EverGrandeCity_ChampionsRoom_Text_Defeat[];
extern const u8 HE_English_221[];
extern const u8 EverGrandeCity_ChampionsRoom_Text_PostBattleSpeech[];
extern const u8 HE_English_222[];
extern const u8 SkyPillar_Top_Text_RayquazaFlewOff[];
extern const u8 HE_English_223[];
extern const u8 OldaleTown_Text_SavingMyProgress[];
extern const u8 HE_English_224[];
extern const u8 OldaleTown_Text_IWorkAtPokemonMart[];
extern const u8 HE_English_225[];
extern const u8 OldaleTown_Text_ThisIsAPokemonMart[];
extern const u8 HE_English_226[];
extern const u8 OldaleTown_Text_WaitDontComeInHere[];
extern const u8 HE_English_227[];
extern const u8 OldaleTown_Text_FinishedSketchingFootprints[];
extern const u8 HE_English_228[];
extern const u8 OldaleTown_Text_MayLetsGoBack[];
extern const u8 HE_English_229[];
extern const u8 OldaleTown_Text_BrendanLetsGoBack[];
extern const u8 HE_English_230[];
extern const u8 HoennExpansion_Text_Research[];
extern const u8 HE_English_231[];
extern const u8 HoennExpansion_Text_ResearchReward[];
extern const u8 HE_English_232[];
extern const u8 HoennExpansion_Text_BagFull[];
extern const u8 HE_English_233[];
extern const u8 HoennExpansion_Text_ResearchComplete[];
extern const u8 HE_English_234[];
extern const u8 LittlerootTown_ProfessorBirchsLab_Text_BirchIsntOneForDeskWork[];
extern const u8 HE_English_235[];
extern const u8 LittlerootTown_ProfessorBirchsLab_Text_BirchEnjoysRivalsHelpToo[];
extern const u8 HE_English_236[];
extern const u8 LittlerootTown_ProfessorBirchsLab_Text_LikeYouToHavePokemon[];
extern const u8 HE_English_237[];
extern const u8 LittlerootTown_ProfessorBirchsLab_Text_MightBeGoodIdeaToGoSeeRival[];
extern const u8 HE_English_238[];
extern const u8 LittlerootTown_ProfessorBirchsLab_Text_GetRivalToTeachYou[];
extern const u8 HE_English_239[];
extern const u8 LittlerootTown_ProfessorBirchsLab_Text_HeardYouBeatRivalTakePokedex[];
extern const u8 HE_English_240[];
extern const u8 LittlerootTown_ProfessorBirchsLab_Text_ExplainPokedex[];
extern const u8 HE_English_241[];
extern const u8 LittlerootTown_ProfessorBirchsLab_Text_CountlessPokemonAwait[];
extern const u8 HE_English_242[];
extern const u8 LittlerootTown_ProfessorBirchsLab_Text_MayGotPokedexTooTakeThese[];
extern const u8 HE_English_243[];
extern const u8 LittlerootTown_ProfessorBirchsLab_Text_CatchCutePokemonWithPokeBalls[];
extern const u8 HE_English_244[];
extern const u8 LittlerootTown_ProfessorBirchsLab_Text_OhYourBagsFull[];
extern const u8 LittlerootTown_ProfessorBirchsLab_Text_HeyYourBagsFull[];
extern const u8 HE_English_245[];
extern const u8 LittlerootTown_ProfessorBirchsLab_Text_BrendanGotPokedexTooTakeThese[];
extern const u8 HE_English_246[];
extern const u8 LittlerootTown_ProfessorBirchsLab_Text_CatchCoolPokemonWithPokeBalls[];
extern const u8 HE_English_247[];
extern const u8 AquaHideout_1F_Text_OurBossIsSnatchingSomething[];
extern const u8 HE_English_248[];
extern const u8 AquaHideout_1F_Text_WhereMightMagmaHideoutBe[];
extern const u8 HE_English_249[];
extern const u8 AquaHideout_1F_Text_BossWentToJackASubmarine[];
extern const u8 HE_English_250[];
extern const u8 AquaHideout_1F_Text_BossIsOnRoute122[];
extern const u8 HE_English_251[];
extern const u8 AquaHideout_1F_Text_TeamMagmaAtMtChimney[];
extern const u8 HE_English_252[];
extern const u8 AquaHideout_1F_Text_BossIsInSlateportCity[];
extern const u8 HE_English_253[];
extern const u8 PetalburgCity_Gym_Text_DadYoureHereWithYourPokemon[];
extern const u8 HE_English_254[];
extern const u8 PetalburgCity_Gym_Text_DadOhYoureWallyRight[];
extern const u8 HE_English_255[];
extern const u8 PetalburgCity_Gym_Text_WallyIveNeverCaughtAPokemon[];
extern const u8 HE_English_256[];
extern const u8 PetalburgCity_Gym_Text_DadHmISee[];
extern const u8 HE_English_257[];
extern const u8 PetalburgCity_Gym_Text_IllLoanYouMyZigzagoon[];
extern const u8 HE_English_258[];
extern const u8 PetalburgCity_Gym_Text_WallyThankYouAndDadGivesPokeBall[];
extern const u8 HE_English_259[];
extern const u8 PetalburgCity_Gym_Text_WallyThankYouBye[];
extern const u8 HE_English_260[];
extern const u8 PetalburgCity_Gym_Text_DadGoCollectBadges[];
extern const u8 HE_English_261[];
extern const u8 PetalburgCity_Gym_Text_NormanGoToRustboro[];
extern const u8 HE_English_262[];
extern const u8 PetalburgCity_Gym_Text_NormanGoToDewford[];
extern const u8 HE_English_263[];
extern const u8 HE_Text_SternMission[];
extern const u8 HE_English_264[];
extern const u8 HE_Text_HarborVesper[];
extern const u8 HE_English_265[];
extern const u8 HE_Text_HarborLose[];
extern const u8 HE_English_266[];
extern const u8 HE_Text_HarborExit[];
extern const u8 HE_English_267[];
extern const u8 HE_Text_SternSaved[];
extern const u8 HE_English_268[];
extern const u8 MagmaHideout_4F_Text_MaxieAwakenGroudon[];
extern const u8 HE_English_269[];
extern const u8 MagmaHideout_4F_Text_MaxieGroudonWhatsWrong[];
extern const u8 HE_English_270[];
extern const u8 MagmaHideout_4F_Text_MaxieOhItWasYou[];
extern const u8 HE_English_271[];
extern const u8 MagmaHideout_4F_Text_MaxieDefeat[];
extern const u8 HE_English_272[];
extern const u8 MagmaHideout_4F_Text_MaxieImGoingAfterGroudon[];
extern const u8 HE_English_273[];
extern const u8 LittlerootTown_Text_OurNewHomeLetsGoInside[];
extern const u8 HE_English_274[];
extern const u8 LittlerootTown_Text_WaitPlayer[];
extern const u8 HE_English_275[];
extern const u8 LittlerootTown_Text_WearTheseRunningShoes[];
extern const u8 HE_English_276[];
extern const u8 LittlerootTown_Text_SwitchShoesWithRunningShoes[];
extern const u8 HE_English_277[];
extern const u8 LittlerootTown_Text_ExplainRunningShoes[];
extern const u8 HE_English_278[];
extern const u8 LittlerootTown_Text_ComeHomeIfAnythingHappens[];
extern const u8 HE_English_279[];
extern const u8 LittlerootTown_Text_IfYouGoInGrassPokemonWillJumpOut[];
extern const u8 HE_English_280[];
extern const u8 LittlerootTown_Text_DangerousIfYouDontHavePokemon[];
extern const u8 HE_English_281[];
extern const u8 LittlerootTown_Text_CanYouGoSeeWhatsHappening[];
extern const u8 HE_English_282[];
extern const u8 LittlerootTown_Text_YouSavedBirch[];
extern const u8 HE_English_283[];
extern const u8 HoennExpansion_Text_LaranjaWelcome[];
extern const u8 HE_English_284[];
extern const u8 HoennExpansion_Text_LaranjaGift[];
extern const u8 HE_English_285[];
extern const u8 HoennExpansion_Text_LaranjaBagFull[];
extern const u8 HE_English_286[];
extern const u8 HoennExpansion_Text_LaranjaChallenge[];
extern const u8 HE_English_287[];
extern const u8 HoennExpansion_Text_LaranjaBattle[];
extern const u8 HE_English_288[];
extern const u8 HoennExpansion_Text_LaranjaDefeated[];
extern const u8 HE_English_289[];
extern const u8 HoennExpansion_Text_LaranjaWait[];
extern const u8 HE_English_290[];
extern const u8 HoennExpansion_Text_LaranjaAfterBattle[];
extern const u8 HE_English_291[];
extern const u8 CaveOfOrigin_B1F_Text_WallaceStory[];
extern const u8 HE_English_292[];
extern const u8 CaveOfOrigin_B1F_Text_WhereIsRayquaza[];
extern const u8 HE_English_293[];
extern const u8 CaveOfOrigin_B1F_Text_ButWereInCaveOfOrigin[];
extern const u8 HE_English_294[];
extern const u8 CaveOfOrigin_B1F_Text_OldLadyDidntMentionThat[];
extern const u8 HE_English_295[];
extern const u8 CaveOfOrigin_B1F_Text_CantYouRememberSomehow[];
extern const u8 HE_English_296[];
extern const u8 CaveOfOrigin_B1F_Text_WellHeadToSkyPillar[];
extern const u8 HE_English_297[];
extern const u8 SeafloorCavern_Room9_Text_ArchieHoldItRightThere[];
extern const u8 HE_English_298[];
extern const u8 SeafloorCavern_Room9_Text_ArchieSoItWasYou[];
extern const u8 HE_English_299[];
extern const u8 SeafloorCavern_Room9_Text_ArchieBeholdKyogre[];
extern const u8 HE_English_300[];
extern const u8 SeafloorCavern_Room9_Text_ArchieYouMustDisappear[];
extern const u8 HE_English_301[];
extern const u8 SeafloorCavern_Room9_Text_ArchieDefeat[];
extern const u8 HE_English_302[];
extern const u8 SeafloorCavern_Room9_Text_ArchieWithThisRedOrb[];
extern const u8 HE_English_303[];
extern const u8 SeafloorCavern_Room9_Text_RedOrbShinesByItself[];
extern const u8 HE_English_304[];
extern const u8 SeafloorCavern_Room9_Text_ArchieWhereDidKyogreGo[];
extern const u8 HE_English_305[];
extern const u8 SeafloorCavern_Room9_Text_ArchieAMessageFromOutside[];
extern const u8 HE_English_306[];
extern const u8 SeafloorCavern_Room9_Text_ArchieWhatRainingTooHard[];
extern const u8 HE_English_307[];
extern const u8 SeafloorCavern_Room9_Text_ArchieWhyDidKyogreDisappear[];
extern const u8 HE_English_308[];
extern const u8 SeafloorCavern_Room9_Text_MaxieWhatHaveYouWrought[];
extern const u8 HE_English_309[];
extern const u8 SeafloorCavern_Room9_Text_ArchieDontGetAllHighAndMighty[];
extern const u8 HE_English_310[];
extern const u8 SeafloorCavern_Room9_Text_MaxieWeDontHaveTimeToArgue[];
extern const u8 HE_English_311[];
extern const u8 SeafloorCavern_Room9_Text_MaxieComeOnPlayer[];
extern const u8 HE_English_312[];
extern const u8 Route119_WeatherInstitute_2F_Text_ShellyIntro[];
extern const u8 HE_English_313[];
extern const u8 Route119_WeatherInstitute_2F_Text_ShellyDefeat[];
extern const u8 HE_English_314[];
extern const u8 Route119_WeatherInstitute_2F_Text_ShellyPostBattle[];
extern const u8 HE_English_315[];
extern const u8 Route119_WeatherInstitute_2F_Text_TeamMagmaJustPassedBy[];
extern const u8 HE_English_316[];
extern const u8 Route119_WeatherInstitute_2F_Text_WeHaveToHurryToMtPyre[];
extern const u8 HE_English_317[];
extern const u8 Route119_WeatherInstitute_2F_Text_ThanksPleaseTakePokemon[];
extern const u8 HE_English_318[];
extern const u8 Route119_WeatherInstitute_2F_Text_NoRoomForPokemon[];
extern const u8 HE_English_319[];
extern const u8 Route119_WeatherInstitute_2F_Text_PokemonChangesWithWeather[];
extern const u8 HE_English_320[];
extern const u8 Route119_WeatherInstitute_2F_Text_ChangingWeatherRidiculous[];
extern const u8 HE_English_321[];
extern const u8 GraniteCave_1F_Text_GetsDarkAheadHereYouGo[];
extern const u8 HE_English_322[];
extern const u8 GraniteCave_1F_Text_ExplainFlash[];
extern const u8 HE_English_323[];
extern const u8 Route104_MrBrineysHouse_Text_ItsYouLetsSailToDewford[];
extern const u8 HE_English_324[];
extern const u8 Route104_MrBrineysHouse_Text_SetSailForDewford[];
extern const u8 HE_English_325[];
extern const u8 Route104_MrBrineysHouse_Text_DeclineDeliverySail[];
extern const u8 HE_English_326[];
extern const u8 Route104_MrBrineysHouse_Text_NeedToMakeDeliveriesSailToDewford[];
extern const u8 Route104_MrBrineysHouse_Text_NeedToDeliverPackageSailToDewford[];
extern const u8 HE_English_327[];
extern const u8 Route104_MrBrineysHouse_Text_TellMeWheneverYouWantToSail[];
extern const u8 Route109_Text_BrineyTellMeWhenYouNeedToSail[];
extern const u8 DewfordTown_Text_JustTellMeWhenYouNeedToSetSail[];
extern const u8 HE_English_328[];
extern const u8 HE_Text_BrineyClosed[];
extern const u8 HE_English_329[];
extern const u8 MtPyre_Summit_Text_Grunt1Intro[];
extern const u8 MtPyre_Summit_Text_Grunt2Intro[];
extern const u8 MtPyre_Summit_Text_Grunt3Intro[];
extern const u8 MtPyre_Summit_Text_Grunt4Intro[];
extern const u8 HE_English_330[];
extern const u8 MtPyre_Summit_Text_Grunt1Defeat[];
extern const u8 MtPyre_Summit_Text_Grunt2Defeat[];
extern const u8 MtPyre_Summit_Text_Grunt3Defeat[];
extern const u8 MtPyre_Summit_Text_Grunt4Defeat[];
extern const u8 HE_English_331[];
extern const u8 MtPyre_Summit_Text_Grunt1PostBattle[];
extern const u8 MtPyre_Summit_Text_Grunt2PostBattle[];
extern const u8 MtPyre_Summit_Text_Grunt3PostBattle[];
extern const u8 MtPyre_Summit_Text_Grunt4PostBattle[];
extern const u8 HE_English_332[];
extern const u8 MtPyre_Summit_Text_ArchieWeGotTheOrbLetsGo[];
extern const u8 HE_English_333[];
extern const u8 MtPyre_Summit_Text_BothOrbsTakenMagmaLeftThis[];
extern const u8 HE_English_334[];
extern const u8 MtPyre_Summit_Text_OrbsHaveBeenTaken[];
extern const u8 HE_English_335[];
extern const u8 MtPyre_Summit_Text_GroudonKyogreAwakened[];
extern const u8 HE_English_336[];
extern const u8 MtPyre_Summit_Text_ThoseTwoMenReturnedOrbs[];
extern const u8 HE_English_337[];
extern const u8 MtPyre_Summit_Text_SuperAncientPokemonTaughtUs[];
extern const u8 HE_English_338[];
extern const u8 MtPyre_Summit_Text_WillYouHearOutMyTale[];
extern const u8 HE_English_339[];
extern const u8 MtPyre_Summit_Text_GroudonKyogreTale[];
extern const u8 HE_English_340[];
extern const u8 MtPyre_Summit_Text_WellThatTooIsFine[];
extern const u8 HE_English_341[];
extern const u8 MtPyre_Summit_Text_MaxieSilence[];
extern const u8 HE_English_342[];
extern const u8 MtPyre_Summit_Text_HearTheNewLegendOfHoenn[];
extern const u8 HE_English_343[];
extern const u8 MtPyre_Summit_Text_HoennTrioTale[];
extern const u8 HE_English_344[];
extern const u8 RustboroCity_Text_SneakyLookingManWentAroundCorner[];
extern const u8 HE_English_345[];
extern const u8 RustboroCity_Text_HaveYouChallengedGym[];
extern const u8 HE_English_346[];
extern const u8 RustboroCity_Text_HeyThatsRustborosGymBadge[];
extern const u8 HE_English_347[];
extern const u8 RustboroCity_Text_GymLeaderIsntEasyWithFire[];
extern const u8 HE_English_348[];
extern const u8 RustboroCity_Text_DevonCorpSign[];
extern const u8 HE_English_349[];
extern const u8 RustboroCity_Text_GymSign[];
extern const u8 HE_English_350[];
extern const u8 RustboroCity_Text_CitySign[];
extern const u8 HE_English_351[];
extern const u8 RustboroCity_Text_TrainersSchoolSign[];
extern const u8 HE_English_352[];
extern const u8 MeteorFalls_1F_1R_Text_WithThisMeteorite[];
extern const u8 HE_English_353[];
extern const u8 MeteorFalls_1F_1R_Text_DontExpectMercyFromMagma[];
extern const u8 HE_English_354[];
extern const u8 MeteorFalls_1F_1R_Text_HoldItRightThereMagma[];
extern const u8 HE_English_355[];
extern const u8 MeteorFalls_1F_1R_Text_BeSeeingYouTeamAqua[];
extern const u8 HE_English_356[];
extern const u8 MeteorFalls_1F_1R_Text_ArchieSeenYouBefore[];
extern const u8 HE_English_357[];
extern const u8 MeteorFalls_1F_1R_Text_BossWeShouldChaseMagma[];
extern const u8 HE_English_358[];
extern const u8 MeteorFalls_1F_1R_Text_ArchieYesNoTellingWhatMagmaWillDo[];
extern const u8 HE_English_359[];
extern const u8 MeteorFalls_1F_1R_Text_ArchieFarewell[];
extern const u8 HE_English_360[];
extern const u8 MeteorFalls_1F_1R_Text_MeetProfCozmo[];
extern const u8 HE_English_361[];
extern const u8 MeteorFalls_1F_1R_Text_WhatsTeamMagmaDoingAtMtChimney[];
extern const u8 HE_English_362[];
extern const u8 PlayersHouse_2F_Text_ClockIsStopped[];
extern const u8 HE_English_363[];
extern const u8 PlayersHouse_2F_Text_HowDoYouLikeYourRoom[];
extern const u8 HE_English_364[];
extern const u8 PlayersHouse_2F_Text_Notebook[];
extern const u8 HE_English_365[];
extern const u8 PlayersHouse_1F_Text_IsntItNiceInHere[];
extern const u8 HE_English_366[];
extern const u8 PlayersHouse_1F_Text_MoversPokemonGoSetClock[];
extern const u8 HE_English_367[];
extern const u8 PlayersHouse_1F_Text_ArentYouInterestedInRoom[];
extern const u8 HE_English_368[];
extern const u8 PlayersHouse_1F_Text_GoSetTheClock[];
extern const u8 HE_English_369[];
extern const u8 PlayersHouse_1F_Text_OhComeQuickly[];
extern const u8 HE_English_370[];
extern const u8 PlayersHouse_1F_Text_MaybeDadWillBeOn[];
extern const u8 HE_English_371[];
extern const u8 PlayersHouse_1F_Text_ItsOverWeMissedHim[];
extern const u8 HE_English_372[];
extern const u8 PlayersHouse_1F_Text_GoIntroduceYourselfNextDoor[];
extern const u8 HE_English_373[];
extern const u8 PlayersHouse_1F_Text_SeeYouHoney[];
extern const u8 HE_English_374[];
extern const u8 PlayersHouse_1F_Text_DidYouMeetProfBirch[];
extern const u8 HE_English_375[];
extern const u8 PlayersHouse_1F_Text_YouShouldRestABit[];
extern const u8 HE_English_376[];
extern const u8 PlayersHouse_1F_Text_TakeCareHoney[];
extern const u8 HE_English_377[];
extern const u8 PlayersHouse_1F_Text_ReportFromPetalburgGym[];
extern const u8 HE_English_378[];
extern const u8 PlayersHouse_1F_Text_TheresAMovieOnTV[];
extern const u8 HE_English_379[];
extern const u8 PlayersHouse_1F_Text_RunningShoesManual[];
extern const u8 HE_English_380[];
extern const u8 AquaHideout_B2F_Text_MattIntro[];
extern const u8 HE_English_381[];
extern const u8 AquaHideout_B2F_Text_OurBossGotThroughHisPreparations[];
extern const u8 HE_English_382[];
extern const u8 AquaHideout_B2F_Text_MattPostBattle[];
extern const u8 HE_English_383[];
extern const u8 DewfordTown_Gym_Text_GymGuideAdvice[];
extern const u8 HE_English_384[];
extern const u8 DewfordTown_Gym_Text_GymGuidePostVictory[];
extern const u8 HE_English_385[];
extern const u8 DewfordTown_Gym_Text_BrawlyIntro[];
extern const u8 HE_English_386[];
extern const u8 DewfordTown_Gym_Text_BrawlyDefeat[];
extern const u8 HE_English_387[];
extern const u8 DewfordTown_Gym_Text_ReceivedKnuckleBadge[];
extern const u8 HE_English_388[];
extern const u8 DewfordTown_Gym_Text_KnuckleBadgeInfoTakeThis[];
extern const u8 HE_English_389[];
extern const u8 DewfordTown_Gym_Text_ExplainBulkUp[];
extern const u8 HE_English_390[];
extern const u8 DewfordTown_Gym_Text_BrawlyPostBattle[];
extern const u8 HE_English_391[];
extern const u8 HE_Text_BrawlyNeedSignal[];
extern const u8 HE_English_392[];
extern const u8 Route103_Text_MayRoute103Pokemon[];
extern const u8 Route103_Text_BrendanRoute103Pokemon[];
extern const u8 HE_English_393[];
extern const u8 Route103_Text_MayLetsBattle[];
extern const u8 Route103_Text_BrendanLetsBattle[];
extern const u8 HE_English_394[];
extern const u8 Route103_Text_MayDefeated[];
extern const u8 Route103_Text_BrendanDefeated[];
extern const u8 HE_English_395[];
extern const u8 Route103_Text_MayTimeToHeadBack[];
extern const u8 Route103_Text_BrendanTimeToHeadBack[];
extern const u8 HE_English_396[];
extern const u8 SlateportCity_Harbor_Text_SameThugsTriedToRobAtMuseum[];
extern const u8 HE_English_397[];
extern const u8 SlateportCity_Harbor_Text_ArchieYouAgainHideoutInLilycove[];
extern const u8 HE_English_398[];
extern const u8 SlateportCity_Harbor_Text_CaptSternWhyStealMySubmarine[];
extern const u8 HE_English_399[];
extern const u8 SlateportCity_Harbor_Text_TeamAquaLeftNeedDive[];
extern const u8 HE_English_400[];
extern const u8 SlateportCity_Harbor_Text_NeedDiveToCatchSub[];
extern const u8 HE_English_401[];
extern const u8 Route110_Text_MayLetsBattle[];
extern const u8 Route110_Text_BrendanLetsBattle[];
extern const u8 HE_English_402[];
extern const u8 Route110_Text_MayDefeated[];
extern const u8 Route110_Text_BrendanDefeated[];
extern const u8 HE_English_403[];
extern const u8 Route110_Text_MayTakeThis[];
extern const u8 Route110_Text_BrendanTakeThis[];
extern const u8 HE_English_404[];
extern const u8 Route110_Text_MayExplainItemfinder[];
extern const u8 Route110_Text_BrendanExplainItemfinder[];
extern const u8 HE_English_405[];
extern const u8 Route110_Text_ImagineSeeingYouHere[];
extern const u8 HE_English_406[];
extern const u8 Route110_Text_HeardYouInstallMatchCall[];
extern const u8 HE_English_407[];
extern const u8 Route110_Text_KeepAnEyeOutForRival[];
extern const u8 HE_English_408[];
extern const u8 LilycoveCity_Text_ChanceToDoBigThings[];
extern const u8 HE_English_409[];
extern const u8 LilycoveCity_Text_IfWorldBecomesOurs[];
extern const u8 HE_English_410[];
extern const u8 LilycoveCity_Text_TeamAquaBeenTrainingWailmer[];
extern const u8 HE_English_411[];
extern const u8 LilycoveCity_Text_SomeonePuntedTeamAquaOut[];
extern const u8 HE_English_412[];
extern const u8 LilycoveCity_Text_TeamAquaRenovatedCavern[];
extern const u8 HE_English_413[];
extern const u8 LilycoveCity_Text_TeamAquaLotGoneForGood[];
extern const u8 HE_English_414[];
extern const u8 PetalburgWoods_Text_NotAOneToBeFound[];
extern const u8 HE_English_415[];
extern const u8 PetalburgWoods_Text_HaveYouSeenShroomish[];
extern const u8 HE_English_416[];
extern const u8 PetalburgWoods_Text_IWasGoingToAmbushYou[];
extern const u8 HE_English_417[];
extern const u8 PetalburgWoods_Text_NoOneCrossesTeamAqua[];
extern const u8 HE_English_418[];
extern const u8 PetalburgWoods_Text_YoureKiddingMe[];
extern const u8 HE_English_419[];
extern const u8 PetalburgWoods_Text_YouveGotSomeNerve[];
extern const u8 HE_English_420[];
extern const u8 PetalburgWoods_Text_ThatWasAwfullyClose[];
extern const u8 HE_English_421[];
extern const u8 PetalburgWoods_Text_TeamAquaAfterSomethingInRustboro[];
extern const u8 HE_English_422[];
extern const u8 PetalburgWoods_Text_ICantBeWastingTime[];
extern const u8 HE_English_423[];
extern const u8 PetalburgWoods_Text_YoureLoadedWithItems[];
extern const u8 HE_English_424[];
extern const u8 PetalburgWoods_Text_ImOutOfPokeBalls[];
extern const u8 HE_English_425[];
extern const u8 PetalburgWoods_Text_InstantlyPopularWithBugPokemon[];
extern const u8 HE_English_426[];
extern const u8 PetalburgWoods_Text_CantBePopularIfILose[];
extern const u8 HE_English_427[];
extern const u8 PetalburgWoods_Text_PeopleRespectYou[];
extern const u8 HE_English_428[];
extern const u8 PetalburgWoods_Text_StayOutOfTallGrass[];
extern const u8 HE_English_429[];
extern const u8 PetalburgWoods_Text_HiddenItemsExplanation[];
extern const u8 HE_English_430[];
extern const u8 RustboroCity_Gym_Text_GymGuideAdvice[];
extern const u8 HE_English_431[];
extern const u8 RustboroCity_Gym_Text_GymGuidePostVictory[];
extern const u8 HE_English_432[];
extern const u8 RustboroCity_Gym_Text_JoshIntro[];
extern const u8 HE_English_433[];
extern const u8 RustboroCity_Gym_Text_JoshPostBattle[];
extern const u8 HE_English_434[];
extern const u8 RustboroCity_Gym_Text_TommyIntro[];
extern const u8 HE_English_435[];
extern const u8 RustboroCity_Gym_Text_TommyDefeat[];
extern const u8 HE_English_436[];
extern const u8 RustboroCity_Gym_Text_TommyPostBattle[];
extern const u8 HE_English_437[];
extern const u8 RustboroCity_Gym_Text_MarcIntro[];
extern const u8 HE_English_438[];
extern const u8 RustboroCity_Gym_Text_MarcDefeat[];
extern const u8 HE_English_439[];
extern const u8 RustboroCity_Gym_Text_MarcPostBattle[];
extern const u8 HE_English_440[];
extern const u8 RustboroCity_Gym_Text_RoxanneIntro[];
extern const u8 HE_English_441[];
extern const u8 RustboroCity_Gym_Text_RoxanneDefeat[];
extern const u8 HE_English_442[];
extern const u8 RustboroCity_Gym_Text_ReceivedStoneBadge[];
extern const u8 HE_English_443[];
extern const u8 RustboroCity_Gym_Text_StoneBadgeInfoTakeThis[];
extern const u8 HE_English_444[];
extern const u8 RustboroCity_Gym_Text_ExplainRockTomb[];
extern const u8 HE_English_445[];
extern const u8 RustboroCity_Gym_Text_RoxannePostBattle[];
extern const u8 HE_English_446[];
extern const u8 RustboroCity_Gym_Text_GymStatue[];
extern const u8 HE_English_447[];
extern const u8 RustboroCity_Gym_Text_GymStatueCertified[];
extern const u8 HE_English_448[];
extern const u8 HE_Text_NoProof[];
extern const u8 HE_English_449[];
extern const u8 HE_Text_Radio[];
extern const u8 HE_English_450[];
extern const u8 HE_Text_RoxanneResistance[];
extern const u8 HE_English_451[];
extern const u8 HE_Text_EndChapter[];
extern const u8 HE_English_452[];
extern const u8 PetalburgCity_Text_WhereIsWally[];
extern const u8 HE_English_453[];
extern const u8 PetalburgCity_Text_AreYouRookieTrainer[];
extern const u8 HE_English_454[];
extern const u8 PetalburgCity_Text_ThisIsPetalburgGym[];
extern const u8 HE_English_455[];
extern const u8 PetalburgCity_Text_ThisIsGymSign[];
extern const u8 HE_English_456[];
extern const u8 PetalburgCity_Text_WaterReflection[];
extern const u8 HE_English_457[];
extern const u8 PetalburgCity_Text_FullPartyExplanation[];
extern const u8 HE_English_458[];
extern const u8 PetalburgCity_Text_AreYouATrainer[];
extern const u8 HE_English_459[];
extern const u8 PetalburgCity_Text_WellMaybeNot[];
extern const u8 HE_English_460[];
extern const u8 PetalburgCity_Text_ImLookingForTalentedTrainers[];
extern const u8 HE_English_461[];
extern const u8 SlateportCity_Text_AquaHasPolicy[];
extern const u8 HE_English_462[];
extern const u8 SlateportCity_Text_AquaWillAssumeControlOfSubmarine[];
extern const u8 HE_English_463[];
extern const u8 SlateportCity_Text_SternWhatWasAllThat[];
extern const u8 HE_English_464[];
extern const u8 SlateportCity_Text_FromHarborTryingToTakeSub[];
extern const u8 HE_English_465[];
extern const u8 Route109_Text_YouCanHaveThis[];
extern const u8 HE_English_466[];
extern const u8 Route101_Text_PleaseHelp[];
extern const u8 HE_English_467[];
extern const u8 Route101_Text_DontLeaveMe[];
extern const u8 HE_English_468[];
extern const u8 Route101_Text_YouSavedMe[];
extern const u8 HE_English_469[];
extern const u8 Route101_Text_TakeTiredPokemonToPokeCenter[];
extern const u8 HE_English_470[];
extern const u8 Route102_Text_LetsGoBack[];
extern const u8 HE_English_471[];
extern const u8 Route102_Text_ImNotVeryTall[];
extern const u8 HE_English_472[];
extern const u8 Route102_Text_CatchWholeBunchOfPokemon[];
extern const u8 HE_English_473[];
extern const u8 DewfordTown_Text_TinyIslandCommunity[];
extern const u8 HE_English_474[];
extern const u8 DewfordTown_Text_PetalburgWereSettingSail2[];
extern const u8 HE_English_475[];
extern const u8 DewfordTown_Text_GoDeliverIllBeWaiting[];
extern const u8 HE_English_476[];
extern const u8 DewfordTown_Text_SlateportWereSettingSail[];
extern const u8 HE_English_477[];
extern const u8 DewfordTown_Text_GettingItchToFish[];
extern const u8 HE_English_478[];
extern const u8 DewfordTown_Text_GiveYouOneOfMyRods[];
extern const u8 HE_English_479[];
extern const u8 DewfordTown_Text_ThrowInFishingAdvice[];
extern const u8 HE_English_480[];
extern const u8 DewfordTown_Text_ThatsTooBadThen[];
extern const u8 HE_English_481[];
extern const u8 DewfordTown_Text_GreatHaulInSomeBigOnes[];
extern const u8 HE_English_482[];
extern const u8 DewfordTown_Text_FishingAdvice[];
extern const u8 HE_English_483[];
extern const u8 HE_Text_DewfordArrival[];
extern const u8 HE_English_484[];
extern const u8 gText_Birch_Welcome[];
extern const u8 HE_English_485[];
extern const u8 gText_Birch_Pokemon[];
extern const u8 HE_English_486[];
extern const u8 gText_Birch_MainSpeech[];
extern const u8 HE_English_487[];
extern const u8 gText_Birch_AndYouAre[];
extern const u8 HE_English_488[];
extern const u8 gText_Birch_BoyOrGirl[];
extern const u8 HE_English_489[];
extern const u8 gText_Birch_WhatsYourName[];
extern const u8 HE_English_490[];
extern const u8 gText_Birch_SoItsPlayer[];
extern const u8 HE_English_491[];
extern const u8 gText_Birch_YourePlayer[];
extern const u8 HE_English_492[];
extern const u8 gText_Birch_AreYouReady[];
extern const u8 HE_English_493[];
extern const u8 DewfordTown_Text_WhereAreWeBound[];
extern const u8 HE_English_494[];
extern const u8 LittlerootTown_ProfessorBirchsLab_Text_ReceivedPokedex[];
extern const u8 HE_English_495[];
extern const u8 MauvilleCity_Text_WallyPleaseBattleMe[];
extern const u8 HE_English_496[];
extern const u8 MtChimney_Text_PlayerRemovedMeteorite[];
extern const u8 HE_English_497[];
extern const u8 OldaleTown_Text_PotionExplanation[];
extern const u8 HE_English_498[];
extern const u8 PetalburgCity_Gym_Text_WallyIdLikeAPokemon[];
extern const u8 HE_English_499[];
extern const u8 PetalburgCity_Gym_Text_WallyOhWowThankYou[];
extern const u8 HE_English_500[];
extern const u8 PetalburgCity_Gym_Text_WouldYouReallyComeWithMe[];
extern const u8 HE_English_501[];
extern const u8 Route104_MrBrineysHouse_Text_WhereAreWeBound[];
extern const u8 HE_English_502[];
extern const u8 Route109_Text_BrineyWhereAreWeBound[];
extern const u8 HE_English_503[];
extern const u8 Route119_WeatherInstitute_2F_Text_PlayerReceivedCastform[];
extern const u8 HE_English_504[];
extern const u8 RustboroCity_Gym_Text_JoshDefeat[];
extern const u8 HE_English_505[];
extern const u8 SootopolisCity_Text_SootopolisDidntGetWrecked[];

static const struct HeTranslation sStoryTranslations[] = {
    {HE_English_0, HE_CoachGift},
    {HE_English_1, HE_CoachEnough},
    {HE_English_2, HE_CoachOff},
    {HE_English_3, HE_CoachBagFullText},
    {HE_English_4, HE_QuestBoardIntro},
    {HE_English_5, HE_QuestTarget},
    {HE_English_6, HE_QuestReplace},
    {HE_English_7, HE_QuestAccepted},
    {HE_English_8, HE_QuestNoActive},
    {HE_English_9, HE_QuestEarlyText},
    {HE_English_10, HE_QuestFinishedRegion},
    {HE_English_11, HE_QuestResearchIntro},
    {HE_English_12, HE_QuestNeedEvidence},
    {HE_English_13, HE_QuestResearchReady},
    {HE_English_14, HE_QuestResearchNight},
    {HE_English_15, HE_QuestBeaconIntro},
    {HE_English_16, HE_QuestNeedResearch},
    {HE_English_17, HE_QuestNeedNight},
    {HE_English_18, HE_QuestSignal},
    {HE_English_19, HE_QuestRetry},
    {HE_English_20, HE_QuestCapturedText},
    {HE_English_21, HE_RainbowRingBagFullText},
    {HE_English_22, HE_RainbowRecoverRingText},
    {HE_English_23, HE_RainbowEarlyText},
    {HE_English_24, HE_RainbowDistress},
    {HE_English_25, HE_RainbowBriefing},
    {HE_English_26, HE_RainbowMeteorHint},
    {HE_English_27, HE_RainbowSpaceHint},
    {HE_English_28, HE_RainbowShipHint},
    {HE_English_29, HE_RainbowSkyHint},
    {HE_English_30, HE_RainbowScoutIntro},
    {HE_English_31, HE_RainbowDefeat},
    {HE_English_32, HE_RainbowScoutAfter},
    {HE_English_33, HE_RainbowVesperIntro},
    {HE_English_34, HE_RainbowVesperAfter},
    {HE_English_35, HE_RainbowShipIntro},
    {HE_English_36, HE_RainbowShipAfter},
    {HE_English_37, HE_RainbowGiovanniIntro},
    {HE_English_38, HE_RainbowGiovanniAfter},
    {HE_English_39, HE_RainbowRayChoice},
    {HE_English_40, HE_RainbowEnding},
    {HE_English_41, HE_RainbowRestored},
    {HE_English_42, HE_RainbowWaitText},
    {HE_English_43, HE_BugMiloIntro},
    {HE_English_44, HE_BugMiloDefeat},
    {HE_English_45, HE_BugMiloAfter},
    {HE_English_46, HE_BugLiaIntro},
    {HE_English_47, HE_BugLiaDefeat},
    {HE_English_48, HE_BugLiaAfter},
    {HE_English_49, HE_PostJournalStartText},
    {HE_English_50, HE_Thermal_Intro},
    {HE_English_51, HE_Thermal_After},
    {HE_English_52, HE_Thermal_Done},
    {HE_English_53, HE_Thermal_Pattern},
    {HE_English_54, HE_ArrivalThermal_Text},
    {HE_English_55, HE_NeedThermal_Text},
    {HE_English_56, HE_Supply_Intro},
    {HE_English_57, HE_Supply_After},
    {HE_English_58, HE_Supply_Done},
    {HE_English_59, HE_Supply_Pattern},
    {HE_English_60, HE_ArrivalSupply_Text},
    {HE_English_61, HE_NeedSupply_Text},
    {HE_English_62, HE_Forest_Intro},
    {HE_English_63, HE_Forest_After},
    {HE_English_64, HE_Forest_Done},
    {HE_English_65, HE_Forest_Pattern},
    {HE_English_66, HE_ArrivalForest_Text},
    {HE_English_67, HE_NeedForest_Text},
    {HE_English_68, HE_Orbit_Intro},
    {HE_English_69, HE_Orbit_After},
    {HE_English_70, HE_Orbit_Done},
    {HE_English_71, HE_Orbit_Pattern},
    {HE_English_72, HE_ArrivalOrbit_Text},
    {HE_English_73, HE_NeedOrbit_Text},
    {HE_English_74, HE_Ocean_Intro},
    {HE_English_75, HE_Ocean_After},
    {HE_English_76, HE_Ocean_Done},
    {HE_English_77, HE_Ocean_Pattern},
    {HE_English_78, HE_ArrivalOcean_Text},
    {HE_English_79, HE_NeedOcean_Text},
    {HE_English_80, HE_RescueReport},
    {HE_English_81, HE_EnergyReport},
    {HE_English_82, HE_RelayDoneReport},
    {HE_English_83, HE_TooEarlyReport},
    {HE_English_84, HE_LiaisonText},
    {HE_English_85, HE_CampaignNextPulse},
    {HE_English_86, HE_CampaignEnemyDefeat},
    {HE_English_87, HE_GiovanniIntro},
    {HE_English_88, HE_GiovanniDefeat},
    {HE_English_89, HE_FinalCentralReport},
    {HE_English_90, HE_FinalCentralNeeded},
    {HE_English_91, HE_EpilogueText},
    {HE_English_92, HE_CampaignGoalText0},
    {HE_English_93, HE_CampaignGoalText1},
    {HE_English_94, HE_CampaignGoalText2},
    {HE_English_95, HE_CampaignGoalText3},
    {HE_English_96, HE_CampaignGoalText4},
    {HE_English_97, HE_CampaignGoalPeekoText},
    {HE_English_98, HE_CampaignGoalDevonText},
    {HE_English_99, HE_CampaignGoalText5},
    {HE_English_100, HE_CampaignGoalText6},
    {HE_English_101, HE_CampaignGoalText7},
    {HE_English_102, HE_CampaignGoalText8},
    {HE_English_103, HE_CampaignGoalText9},
    {HE_English_104, HE_CampaignGoalText10},
    {HE_English_105, HE_CampaignGoalText11},
    {HE_English_106, HE_CampaignGoalText12},
    {HE_English_107, HE_CampaignGoalText13},
    {HE_English_108, HE_CampaignGoalText14},
    {HE_English_109, HE_CampaignGoalText15},
    {HE_English_110, HE_CampaignGoalText16},
    {HE_English_111, HE_CampaignGoalText17},
    {HE_English_112, HE_CampaignGoalText18},
    {HE_English_113, HE_CampaignGoalText19},
    {HE_English_114, HE_CampaignGoalText20},
    {HE_English_115, HE_CampaignDoneText},
    {HE_English_116, HE_Text_Journal},
    {HE_English_117, HE_Text_GoalRustboro},
    {HE_English_118, HE_Text_GoalDewford},
    {HE_English_119, HE_Text_GoalBrawly},
    {HE_English_120, HE_Text_GoalHarbor},
    {HE_English_121, HE_Text_GoalMauville},
    {HE_English_122, HE_Text_GoalWattson},
    {HE_English_123, HE_Text_GoalEnd},
    {HE_English_124, HE_Text_Decoder},
    {HE_English_125, HE_Text_DecoderHow},
    {HE_English_126, HE_Text_Early},
    {HE_English_127, HE_Text_Medic},
    {HE_English_128, HE_Text_Healed},
    {HE_English_129, HE_Text_PuzzleWrong},
    {HE_English_130, HE_Text_PuzzleDone},
    {HE_English_131, HE_Text_NoDecoder},
    {HE_English_132, HE_Text_NextPulse},
    {HE_English_133, HE_Text_PatternRustboro},
    {HE_English_134, HE_Text_RelayRustboroOff},
    {HE_English_135, HE_Text_PatternDewford},
    {HE_English_136, HE_Text_RelayDewfordOff},
    {HE_English_137, HE_Text_PatternMauville},
    {HE_English_138, HE_Text_RelayMauvilleOff},
    {HE_English_139, HE_Text_CaveGuard},
    {HE_English_140, HE_Text_CaveGuardLose},
    {HE_English_141, HE_Text_GeneratorVesper},
    {HE_English_142, HE_Text_GeneratorLose},
    {HE_English_143, HE_Text_NeedHarbor},
    {HE_English_144, HeRebuild_Text_Officer},
    {HE_English_145, MossdeepCity_SpaceCenter_2F_Text_WhyWouldMagmaStealRocketFuel},
    {HE_English_146, MossdeepCity_SpaceCenter_2F_Text_MagmaCantGetAwayWithThis},
    {HE_English_147, MossdeepCity_SpaceCenter_2F_Text_YoureOutnumberedTakeUsOn},
    {HE_English_148, MossdeepCity_SpaceCenter_2F_Text_GoodAnswer},
    {HE_English_149, MossdeepCity_SpaceCenter_2F_Text_Grunt5Intro},
    {HE_English_149, MossdeepCity_SpaceCenter_2F_Text_Grunt6Intro},
    {HE_English_149, MossdeepCity_SpaceCenter_2F_Text_Grunt7Intro},
    {HE_English_149, MtChimney_Text_TabithaIntro},
    {HE_English_149, MtChimney_Text_Grunt2Intro},
    {HE_English_149, MtChimney_Text_Grunt1Intro},
    {HE_English_149, MagmaHideout_4F_Text_Grunt11Intro},
    {HE_English_149, MagmaHideout_4F_Text_Grunt12Intro},
    {HE_English_149, MagmaHideout_4F_Text_Grunt13Intro},
    {HE_English_149, MagmaHideout_4F_Text_TabithaIntro},
    {HE_English_149, Route119_WeatherInstitute_2F_Text_Grunt2Intro},
    {HE_English_149, Route119_WeatherInstitute_2F_Text_Grunt3Intro},
    {HE_English_149, Route119_WeatherInstitute_2F_Text_Grunt5Intro},
    {HE_English_150, MossdeepCity_SpaceCenter_2F_Text_Grunt5Defeat},
    {HE_English_150, MossdeepCity_SpaceCenter_2F_Text_Grunt6Defeat},
    {HE_English_150, MossdeepCity_SpaceCenter_2F_Text_Grunt7Defeat},
    {HE_English_150, MossdeepCity_SpaceCenter_Text_TabithaDefeat},
    {HE_English_150, MtChimney_Text_TabithaDefeat},
    {HE_English_150, MtChimney_Text_Grunt2Defeat},
    {HE_English_150, MtChimney_Text_Grunt1Defeat},
    {HE_English_150, MagmaHideout_4F_Text_Grunt11Defeat},
    {HE_English_150, MagmaHideout_4F_Text_Grunt12Defeat},
    {HE_English_150, MagmaHideout_4F_Text_Grunt13Defeat},
    {HE_English_150, MagmaHideout_4F_Text_TabithaDefeat},
    {HE_English_150, Route119_WeatherInstitute_2F_Text_Grunt2Defeat},
    {HE_English_150, Route119_WeatherInstitute_2F_Text_Grunt3Defeat},
    {HE_English_150, Route119_WeatherInstitute_2F_Text_Grunt5Defeat},
    {HE_English_151, MossdeepCity_SpaceCenter_2F_Text_Grunt6PostBattle},
    {HE_English_151, MossdeepCity_SpaceCenter_2F_Text_Grunt7PostBattle},
    {HE_English_151, MossdeepCity_SpaceCenter_2F_Text_Grunt5PostBattle},
    {HE_English_151, MtChimney_Text_TabithaPostBattle},
    {HE_English_151, MtChimney_Text_Grunt2PostBattle},
    {HE_English_151, MtChimney_Text_Grunt1PostBattle},
    {HE_English_151, MagmaHideout_4F_Text_Grunt11PostBattle},
    {HE_English_151, MagmaHideout_4F_Text_Grunt12PostBattle},
    {HE_English_151, MagmaHideout_4F_Text_Grunt13PostBattle},
    {HE_English_151, MagmaHideout_4F_Text_TabithaPostBattle},
    {HE_English_151, Route119_WeatherInstitute_2F_Text_Grunt2PostBattle},
    {HE_English_151, Route119_WeatherInstitute_2F_Text_Grunt3PostBattle},
    {HE_English_151, Route119_WeatherInstitute_2F_Text_Grunt5PostBattle},
    {HE_English_152, MossdeepCity_SpaceCenter_2F_Text_WellTakeCareOfYou},
    {HE_English_153, MossdeepCity_SpaceCenter_2F_Text_MaxieDontInterfere},
    {HE_English_154, MossdeepCity_SpaceCenter_2F_Text_StevenWhyStealRocketFuel},
    {HE_English_155, MossdeepCity_SpaceCenter_2F_Text_MaxieUseFuelToEruptVolcano},
    {HE_English_156, MossdeepCity_SpaceCenter_2F_Text_StevenAreYouReadyToBattle},
    {HE_English_157, MossdeepCity_SpaceCenter_2F_Text_StevenHurryGetReadyQuickly},
    {HE_English_158, MossdeepCity_SpaceCenter_2F_Text_MaxieWeFailedIsAquaAlsoMisguided},
    {HE_English_159, MossdeepCity_SpaceCenter_2F_Text_MaxieWeWillGiveUp},
    {HE_English_160, MossdeepCity_SpaceCenter_2F_Text_StevenThankYouComeSeeMeAtHome},
    {HE_English_161, MtChimney_Text_MaxieIntro},
    {HE_English_162, MtChimney_Text_MaxieDefeat},
    {HE_English_163, MtChimney_Text_MaxieYouHaventSeenLastOfMagma},
    {HE_English_164, MtChimney_Text_ArchieGoStopTeamMagma},
    {HE_English_165, MtChimney_Text_ArchieIHaveMyHandsFull},
    {HE_English_166, MtChimney_Text_ArchieThankYou},
    {HE_English_167, MtChimney_Text_MeteoriteFittedOnMachine},
    {HE_English_168, MtChimney_Text_MachineMakesNoResponse},
    {HE_English_169, SootopolisCity_Text_CitySign},
    {HE_English_170, SootopolisCity_Text_WhereDidLegendariesGo},
    {HE_English_171, SootopolisCity_Text_GroudonPleaseStop},
    {HE_English_172, SootopolisCity_Text_AfterAllOurScheming},
    {HE_English_173, SootopolisCity_Text_TryingMeaninglessToPokemon},
    {HE_English_174, SootopolisCity_Text_InvolvedWithCrisisComeWithMe},
    {HE_English_175, SootopolisCity_Text_DoesThisMakeYourFearPokemon},
    {HE_English_176, SootopolisCity_Text_HereWereAreHelpWallace},
    {HE_English_177, SootopolisCity_Text_KnowWhatsNeededToHelpHim},
    {HE_English_178, SootopolisCity_Text_NeverBeenToSkyPillar},
    {HE_English_179, SootopolisCity_Text_SoThatsRayquaza},
    {HE_English_180, SootopolisCity_Text_MaxieArchieLeft},
    {HE_English_181, SootopolisCity_Text_AquaMagmaDidntMeanHarm},
    {HE_English_182, SootopolisCity_Text_ThankYouForHelpAcceptThis},
    {HE_English_183, SootopolisCity_Text_ExplainWaterfallGoToGym},
    {HE_English_184, MauvilleCity_Gym_Text_GymGuideAdvice},
    {HE_English_185, MauvilleCity_Gym_Text_GymGuidePostVictory},
    {HE_English_186, MauvilleCity_Gym_Text_KirkIntro},
    {HE_English_186, MauvilleCity_Gym_Text_ShawnIntro},
    {HE_English_186, MauvilleCity_Gym_Text_BenIntro},
    {HE_English_186, MauvilleCity_Gym_Text_VivianIntro},
    {HE_English_186, MauvilleCity_Gym_Text_AngeloIntro},
    {HE_English_186, DewfordTown_Gym_Text_TakaoIntro},
    {HE_English_186, DewfordTown_Gym_Text_JocelynIntro},
    {HE_English_186, DewfordTown_Gym_Text_LauraIntro},
    {HE_English_186, DewfordTown_Gym_Text_LilithIntro},
    {HE_English_186, DewfordTown_Gym_Text_BrendenIntro},
    {HE_English_186, DewfordTown_Gym_Text_CristianIntro},
    {HE_English_187, MauvilleCity_Gym_Text_KirkDefeat},
    {HE_English_187, MauvilleCity_Gym_Text_ShawnDefeat},
    {HE_English_187, MauvilleCity_Gym_Text_BenDefeat},
    {HE_English_187, MauvilleCity_Gym_Text_VivianDefeat},
    {HE_English_187, MauvilleCity_Gym_Text_AngeloDefeat},
    {HE_English_187, DewfordTown_Gym_Text_TakaoDefeat},
    {HE_English_187, DewfordTown_Gym_Text_JocelynDefeat},
    {HE_English_187, DewfordTown_Gym_Text_LauraDefeat},
    {HE_English_187, DewfordTown_Gym_Text_LilithDefeat},
    {HE_English_187, DewfordTown_Gym_Text_BrendenDefeat},
    {HE_English_187, DewfordTown_Gym_Text_CristianDefeat},
    {HE_English_188, MauvilleCity_Gym_Text_KirkPostBattle},
    {HE_English_188, MauvilleCity_Gym_Text_ShawnPostBattle},
    {HE_English_188, MauvilleCity_Gym_Text_BenPostBattle},
    {HE_English_188, MauvilleCity_Gym_Text_VivianPostBattle},
    {HE_English_188, MauvilleCity_Gym_Text_AngeloPostBattle},
    {HE_English_188, DewfordTown_Gym_Text_TakaoPostBattle},
    {HE_English_188, DewfordTown_Gym_Text_JocelynPostBattle},
    {HE_English_188, DewfordTown_Gym_Text_LauraPostBattle},
    {HE_English_188, DewfordTown_Gym_Text_LilithPostBattle},
    {HE_English_188, DewfordTown_Gym_Text_BrendenPostBattle},
    {HE_English_188, DewfordTown_Gym_Text_CristianPostBattle},
    {HE_English_189, MauvilleCity_Gym_Text_WattsonIntro},
    {HE_English_190, MauvilleCity_Gym_Text_WattsonDefeat},
    {HE_English_191, MauvilleCity_Gym_Text_ReceivedDynamoBadge},
    {HE_English_192, MauvilleCity_Gym_Text_ExplainDynamoBadgeTakeThis},
    {HE_English_193, MauvilleCity_Gym_Text_ExplainShockWave},
    {HE_English_194, MauvilleCity_Gym_Text_WattsonPostBattle},
    {HE_English_195, MauvilleCity_Gym_Text_WattsonGoForthAndEndeavor},
    {HE_English_196, HE_Text_WattsonNeedSignal},
    {HE_English_197, HE_Text_Act3Radio},
    {HE_English_198, HE_Text_Act3Wattson},
    {HE_English_199, HE_Text_Act3End},
    {HE_English_200, RivalsHouse_1F_Text_OhYoureTheNewNeighbor},
    {HE_English_201, RivalsHouse_1F_Text_TooBusyToNoticeVisit},
    {HE_English_202, RivalsHouse_1F_Text_MayWhoAreYou},
    {HE_English_202, RivalsHouse_2F_Text_MayWhoAreYou},
    {HE_English_203, RivalsHouse_1F_Text_BrendanWhoAreYou},
    {HE_English_203, RivalsHouse_2F_Text_BrendanWhoAreYou},
    {HE_English_204, RivalsHouse_1F_Text_DoYouHavePokemon},
    {HE_English_205, AquaHideout_B1F_Text_Grunt2Intro},
    {HE_English_205, AquaHideout_B1F_Text_Grunt3Intro},
    {HE_English_205, AquaHideout_B1F_Text_Grunt5Intro},
    {HE_English_205, AquaHideout_B1F_Text_Grunt7Intro},
    {HE_English_205, AquaHideout_B2F_Text_Grunt4Intro},
    {HE_English_205, AquaHideout_B2F_Text_Grunt6Intro},
    {HE_English_205, AquaHideout_B2F_Text_Grunt8Intro},
    {HE_English_206, AquaHideout_B1F_Text_Grunt2Defeat},
    {HE_English_206, AquaHideout_B1F_Text_Grunt3Defeat},
    {HE_English_206, AquaHideout_B1F_Text_Grunt5Defeat},
    {HE_English_206, AquaHideout_B1F_Text_Grunt7Defeat},
    {HE_English_206, AquaHideout_B2F_Text_Grunt4Defeat},
    {HE_English_206, AquaHideout_B2F_Text_Grunt6Defeat},
    {HE_English_206, AquaHideout_B2F_Text_Grunt8Defeat},
    {HE_English_207, AquaHideout_B1F_Text_Grunt2PostBattle},
    {HE_English_207, AquaHideout_B1F_Text_Grunt3PostBattle},
    {HE_English_207, AquaHideout_B1F_Text_Grunt5PostBattle},
    {HE_English_207, AquaHideout_B1F_Text_Grunt7PostBattle},
    {HE_English_207, AquaHideout_B2F_Text_Grunt4PostBattle},
    {HE_English_207, AquaHideout_B2F_Text_Grunt6PostBattle},
    {HE_English_207, AquaHideout_B2F_Text_Grunt8PostBattle},
    {HE_English_208, MauvilleCity_Text_UncleYourePushingIt},
    {HE_English_209, MauvilleCity_Text_WallyWillYouBattleMe},
    {HE_English_210, MauvilleCity_Text_WallyMyUncleWontKnowImStrong},
    {HE_English_211, MauvilleCity_Text_WallyHereICome},
    {HE_English_212, MauvilleCity_Text_WallyDefeat},
    {HE_English_213, MauvilleCity_Text_WallyIllGoBackToVerdanturf},
    {HE_English_214, MauvilleCity_Text_ThankYouNotEnoughToBattle},
    {HE_English_215, MauvilleCity_Text_UncleNoNeedToBeDown},
    {HE_English_216, MauvilleCity_Text_WallyPokenavCall},
    {HE_English_217, MauvilleCity_Text_ScottYouDidntHoldBack},
    {HE_English_218, HE_Text_MauvilleArrival},
    {HE_English_219, EverGrandeCity_ChampionsRoom_Text_IntroSpeech},
    {HE_English_220, EverGrandeCity_ChampionsRoom_Text_Defeat},
    {HE_English_221, EverGrandeCity_ChampionsRoom_Text_PostBattleSpeech},
    {HE_English_222, SkyPillar_Top_Text_RayquazaFlewOff},
    {HE_English_223, OldaleTown_Text_SavingMyProgress},
    {HE_English_224, OldaleTown_Text_IWorkAtPokemonMart},
    {HE_English_225, OldaleTown_Text_ThisIsAPokemonMart},
    {HE_English_226, OldaleTown_Text_WaitDontComeInHere},
    {HE_English_227, OldaleTown_Text_FinishedSketchingFootprints},
    {HE_English_228, OldaleTown_Text_MayLetsGoBack},
    {HE_English_229, OldaleTown_Text_BrendanLetsGoBack},
    {HE_English_230, HoennExpansion_Text_Research},
    {HE_English_231, HoennExpansion_Text_ResearchReward},
    {HE_English_232, HoennExpansion_Text_BagFull},
    {HE_English_233, HoennExpansion_Text_ResearchComplete},
    {HE_English_234, LittlerootTown_ProfessorBirchsLab_Text_BirchIsntOneForDeskWork},
    {HE_English_235, LittlerootTown_ProfessorBirchsLab_Text_BirchEnjoysRivalsHelpToo},
    {HE_English_236, LittlerootTown_ProfessorBirchsLab_Text_LikeYouToHavePokemon},
    {HE_English_237, LittlerootTown_ProfessorBirchsLab_Text_MightBeGoodIdeaToGoSeeRival},
    {HE_English_238, LittlerootTown_ProfessorBirchsLab_Text_GetRivalToTeachYou},
    {HE_English_239, LittlerootTown_ProfessorBirchsLab_Text_HeardYouBeatRivalTakePokedex},
    {HE_English_240, LittlerootTown_ProfessorBirchsLab_Text_ExplainPokedex},
    {HE_English_241, LittlerootTown_ProfessorBirchsLab_Text_CountlessPokemonAwait},
    {HE_English_242, LittlerootTown_ProfessorBirchsLab_Text_MayGotPokedexTooTakeThese},
    {HE_English_243, LittlerootTown_ProfessorBirchsLab_Text_CatchCutePokemonWithPokeBalls},
    {HE_English_244, LittlerootTown_ProfessorBirchsLab_Text_OhYourBagsFull},
    {HE_English_244, LittlerootTown_ProfessorBirchsLab_Text_HeyYourBagsFull},
    {HE_English_245, LittlerootTown_ProfessorBirchsLab_Text_BrendanGotPokedexTooTakeThese},
    {HE_English_246, LittlerootTown_ProfessorBirchsLab_Text_CatchCoolPokemonWithPokeBalls},
    {HE_English_247, AquaHideout_1F_Text_OurBossIsSnatchingSomething},
    {HE_English_248, AquaHideout_1F_Text_WhereMightMagmaHideoutBe},
    {HE_English_249, AquaHideout_1F_Text_BossWentToJackASubmarine},
    {HE_English_250, AquaHideout_1F_Text_BossIsOnRoute122},
    {HE_English_251, AquaHideout_1F_Text_TeamMagmaAtMtChimney},
    {HE_English_252, AquaHideout_1F_Text_BossIsInSlateportCity},
    {HE_English_253, PetalburgCity_Gym_Text_DadYoureHereWithYourPokemon},
    {HE_English_254, PetalburgCity_Gym_Text_DadOhYoureWallyRight},
    {HE_English_255, PetalburgCity_Gym_Text_WallyIveNeverCaughtAPokemon},
    {HE_English_256, PetalburgCity_Gym_Text_DadHmISee},
    {HE_English_257, PetalburgCity_Gym_Text_IllLoanYouMyZigzagoon},
    {HE_English_258, PetalburgCity_Gym_Text_WallyThankYouAndDadGivesPokeBall},
    {HE_English_259, PetalburgCity_Gym_Text_WallyThankYouBye},
    {HE_English_260, PetalburgCity_Gym_Text_DadGoCollectBadges},
    {HE_English_261, PetalburgCity_Gym_Text_NormanGoToRustboro},
    {HE_English_262, PetalburgCity_Gym_Text_NormanGoToDewford},
    {HE_English_263, HE_Text_SternMission},
    {HE_English_264, HE_Text_HarborVesper},
    {HE_English_265, HE_Text_HarborLose},
    {HE_English_266, HE_Text_HarborExit},
    {HE_English_267, HE_Text_SternSaved},
    {HE_English_268, MagmaHideout_4F_Text_MaxieAwakenGroudon},
    {HE_English_269, MagmaHideout_4F_Text_MaxieGroudonWhatsWrong},
    {HE_English_270, MagmaHideout_4F_Text_MaxieOhItWasYou},
    {HE_English_271, MagmaHideout_4F_Text_MaxieDefeat},
    {HE_English_272, MagmaHideout_4F_Text_MaxieImGoingAfterGroudon},
    {HE_English_273, LittlerootTown_Text_OurNewHomeLetsGoInside},
    {HE_English_274, LittlerootTown_Text_WaitPlayer},
    {HE_English_275, LittlerootTown_Text_WearTheseRunningShoes},
    {HE_English_276, LittlerootTown_Text_SwitchShoesWithRunningShoes},
    {HE_English_277, LittlerootTown_Text_ExplainRunningShoes},
    {HE_English_278, LittlerootTown_Text_ComeHomeIfAnythingHappens},
    {HE_English_279, LittlerootTown_Text_IfYouGoInGrassPokemonWillJumpOut},
    {HE_English_280, LittlerootTown_Text_DangerousIfYouDontHavePokemon},
    {HE_English_281, LittlerootTown_Text_CanYouGoSeeWhatsHappening},
    {HE_English_282, LittlerootTown_Text_YouSavedBirch},
    {HE_English_283, HoennExpansion_Text_LaranjaWelcome},
    {HE_English_284, HoennExpansion_Text_LaranjaGift},
    {HE_English_285, HoennExpansion_Text_LaranjaBagFull},
    {HE_English_286, HoennExpansion_Text_LaranjaChallenge},
    {HE_English_287, HoennExpansion_Text_LaranjaBattle},
    {HE_English_288, HoennExpansion_Text_LaranjaDefeated},
    {HE_English_289, HoennExpansion_Text_LaranjaWait},
    {HE_English_290, HoennExpansion_Text_LaranjaAfterBattle},
    {HE_English_291, CaveOfOrigin_B1F_Text_WallaceStory},
    {HE_English_292, CaveOfOrigin_B1F_Text_WhereIsRayquaza},
    {HE_English_293, CaveOfOrigin_B1F_Text_ButWereInCaveOfOrigin},
    {HE_English_294, CaveOfOrigin_B1F_Text_OldLadyDidntMentionThat},
    {HE_English_295, CaveOfOrigin_B1F_Text_CantYouRememberSomehow},
    {HE_English_296, CaveOfOrigin_B1F_Text_WellHeadToSkyPillar},
    {HE_English_297, SeafloorCavern_Room9_Text_ArchieHoldItRightThere},
    {HE_English_298, SeafloorCavern_Room9_Text_ArchieSoItWasYou},
    {HE_English_299, SeafloorCavern_Room9_Text_ArchieBeholdKyogre},
    {HE_English_300, SeafloorCavern_Room9_Text_ArchieYouMustDisappear},
    {HE_English_301, SeafloorCavern_Room9_Text_ArchieDefeat},
    {HE_English_302, SeafloorCavern_Room9_Text_ArchieWithThisRedOrb},
    {HE_English_303, SeafloorCavern_Room9_Text_RedOrbShinesByItself},
    {HE_English_304, SeafloorCavern_Room9_Text_ArchieWhereDidKyogreGo},
    {HE_English_305, SeafloorCavern_Room9_Text_ArchieAMessageFromOutside},
    {HE_English_306, SeafloorCavern_Room9_Text_ArchieWhatRainingTooHard},
    {HE_English_307, SeafloorCavern_Room9_Text_ArchieWhyDidKyogreDisappear},
    {HE_English_308, SeafloorCavern_Room9_Text_MaxieWhatHaveYouWrought},
    {HE_English_309, SeafloorCavern_Room9_Text_ArchieDontGetAllHighAndMighty},
    {HE_English_310, SeafloorCavern_Room9_Text_MaxieWeDontHaveTimeToArgue},
    {HE_English_311, SeafloorCavern_Room9_Text_MaxieComeOnPlayer},
    {HE_English_312, Route119_WeatherInstitute_2F_Text_ShellyIntro},
    {HE_English_313, Route119_WeatherInstitute_2F_Text_ShellyDefeat},
    {HE_English_314, Route119_WeatherInstitute_2F_Text_ShellyPostBattle},
    {HE_English_315, Route119_WeatherInstitute_2F_Text_TeamMagmaJustPassedBy},
    {HE_English_316, Route119_WeatherInstitute_2F_Text_WeHaveToHurryToMtPyre},
    {HE_English_317, Route119_WeatherInstitute_2F_Text_ThanksPleaseTakePokemon},
    {HE_English_318, Route119_WeatherInstitute_2F_Text_NoRoomForPokemon},
    {HE_English_319, Route119_WeatherInstitute_2F_Text_PokemonChangesWithWeather},
    {HE_English_320, Route119_WeatherInstitute_2F_Text_ChangingWeatherRidiculous},
    {HE_English_321, GraniteCave_1F_Text_GetsDarkAheadHereYouGo},
    {HE_English_322, GraniteCave_1F_Text_ExplainFlash},
    {HE_English_323, Route104_MrBrineysHouse_Text_ItsYouLetsSailToDewford},
    {HE_English_324, Route104_MrBrineysHouse_Text_SetSailForDewford},
    {HE_English_325, Route104_MrBrineysHouse_Text_DeclineDeliverySail},
    {HE_English_326, Route104_MrBrineysHouse_Text_NeedToMakeDeliveriesSailToDewford},
    {HE_English_326, Route104_MrBrineysHouse_Text_NeedToDeliverPackageSailToDewford},
    {HE_English_327, Route104_MrBrineysHouse_Text_TellMeWheneverYouWantToSail},
    {HE_English_327, Route109_Text_BrineyTellMeWhenYouNeedToSail},
    {HE_English_327, DewfordTown_Text_JustTellMeWhenYouNeedToSetSail},
    {HE_English_328, HE_Text_BrineyClosed},
    {HE_English_329, MtPyre_Summit_Text_Grunt1Intro},
    {HE_English_329, MtPyre_Summit_Text_Grunt2Intro},
    {HE_English_329, MtPyre_Summit_Text_Grunt3Intro},
    {HE_English_329, MtPyre_Summit_Text_Grunt4Intro},
    {HE_English_330, MtPyre_Summit_Text_Grunt1Defeat},
    {HE_English_330, MtPyre_Summit_Text_Grunt2Defeat},
    {HE_English_330, MtPyre_Summit_Text_Grunt3Defeat},
    {HE_English_330, MtPyre_Summit_Text_Grunt4Defeat},
    {HE_English_331, MtPyre_Summit_Text_Grunt1PostBattle},
    {HE_English_331, MtPyre_Summit_Text_Grunt2PostBattle},
    {HE_English_331, MtPyre_Summit_Text_Grunt3PostBattle},
    {HE_English_331, MtPyre_Summit_Text_Grunt4PostBattle},
    {HE_English_332, MtPyre_Summit_Text_ArchieWeGotTheOrbLetsGo},
    {HE_English_333, MtPyre_Summit_Text_BothOrbsTakenMagmaLeftThis},
    {HE_English_334, MtPyre_Summit_Text_OrbsHaveBeenTaken},
    {HE_English_335, MtPyre_Summit_Text_GroudonKyogreAwakened},
    {HE_English_336, MtPyre_Summit_Text_ThoseTwoMenReturnedOrbs},
    {HE_English_337, MtPyre_Summit_Text_SuperAncientPokemonTaughtUs},
    {HE_English_338, MtPyre_Summit_Text_WillYouHearOutMyTale},
    {HE_English_339, MtPyre_Summit_Text_GroudonKyogreTale},
    {HE_English_340, MtPyre_Summit_Text_WellThatTooIsFine},
    {HE_English_341, MtPyre_Summit_Text_MaxieSilence},
    {HE_English_342, MtPyre_Summit_Text_HearTheNewLegendOfHoenn},
    {HE_English_343, MtPyre_Summit_Text_HoennTrioTale},
    {HE_English_344, RustboroCity_Text_SneakyLookingManWentAroundCorner},
    {HE_English_345, RustboroCity_Text_HaveYouChallengedGym},
    {HE_English_346, RustboroCity_Text_HeyThatsRustborosGymBadge},
    {HE_English_347, RustboroCity_Text_GymLeaderIsntEasyWithFire},
    {HE_English_348, RustboroCity_Text_DevonCorpSign},
    {HE_English_349, RustboroCity_Text_GymSign},
    {HE_English_350, RustboroCity_Text_CitySign},
    {HE_English_351, RustboroCity_Text_TrainersSchoolSign},
    {HE_English_352, MeteorFalls_1F_1R_Text_WithThisMeteorite},
    {HE_English_353, MeteorFalls_1F_1R_Text_DontExpectMercyFromMagma},
    {HE_English_354, MeteorFalls_1F_1R_Text_HoldItRightThereMagma},
    {HE_English_355, MeteorFalls_1F_1R_Text_BeSeeingYouTeamAqua},
    {HE_English_356, MeteorFalls_1F_1R_Text_ArchieSeenYouBefore},
    {HE_English_357, MeteorFalls_1F_1R_Text_BossWeShouldChaseMagma},
    {HE_English_358, MeteorFalls_1F_1R_Text_ArchieYesNoTellingWhatMagmaWillDo},
    {HE_English_359, MeteorFalls_1F_1R_Text_ArchieFarewell},
    {HE_English_360, MeteorFalls_1F_1R_Text_MeetProfCozmo},
    {HE_English_361, MeteorFalls_1F_1R_Text_WhatsTeamMagmaDoingAtMtChimney},
    {HE_English_362, PlayersHouse_2F_Text_ClockIsStopped},
    {HE_English_363, PlayersHouse_2F_Text_HowDoYouLikeYourRoom},
    {HE_English_364, PlayersHouse_2F_Text_Notebook},
    {HE_English_365, PlayersHouse_1F_Text_IsntItNiceInHere},
    {HE_English_366, PlayersHouse_1F_Text_MoversPokemonGoSetClock},
    {HE_English_367, PlayersHouse_1F_Text_ArentYouInterestedInRoom},
    {HE_English_368, PlayersHouse_1F_Text_GoSetTheClock},
    {HE_English_369, PlayersHouse_1F_Text_OhComeQuickly},
    {HE_English_370, PlayersHouse_1F_Text_MaybeDadWillBeOn},
    {HE_English_371, PlayersHouse_1F_Text_ItsOverWeMissedHim},
    {HE_English_372, PlayersHouse_1F_Text_GoIntroduceYourselfNextDoor},
    {HE_English_373, PlayersHouse_1F_Text_SeeYouHoney},
    {HE_English_374, PlayersHouse_1F_Text_DidYouMeetProfBirch},
    {HE_English_375, PlayersHouse_1F_Text_YouShouldRestABit},
    {HE_English_376, PlayersHouse_1F_Text_TakeCareHoney},
    {HE_English_377, PlayersHouse_1F_Text_ReportFromPetalburgGym},
    {HE_English_378, PlayersHouse_1F_Text_TheresAMovieOnTV},
    {HE_English_379, PlayersHouse_1F_Text_RunningShoesManual},
    {HE_English_380, AquaHideout_B2F_Text_MattIntro},
    {HE_English_381, AquaHideout_B2F_Text_OurBossGotThroughHisPreparations},
    {HE_English_382, AquaHideout_B2F_Text_MattPostBattle},
    {HE_English_383, DewfordTown_Gym_Text_GymGuideAdvice},
    {HE_English_384, DewfordTown_Gym_Text_GymGuidePostVictory},
    {HE_English_385, DewfordTown_Gym_Text_BrawlyIntro},
    {HE_English_386, DewfordTown_Gym_Text_BrawlyDefeat},
    {HE_English_387, DewfordTown_Gym_Text_ReceivedKnuckleBadge},
    {HE_English_388, DewfordTown_Gym_Text_KnuckleBadgeInfoTakeThis},
    {HE_English_389, DewfordTown_Gym_Text_ExplainBulkUp},
    {HE_English_390, DewfordTown_Gym_Text_BrawlyPostBattle},
    {HE_English_391, HE_Text_BrawlyNeedSignal},
    {HE_English_392, Route103_Text_MayRoute103Pokemon},
    {HE_English_392, Route103_Text_BrendanRoute103Pokemon},
    {HE_English_393, Route103_Text_MayLetsBattle},
    {HE_English_393, Route103_Text_BrendanLetsBattle},
    {HE_English_394, Route103_Text_MayDefeated},
    {HE_English_394, Route103_Text_BrendanDefeated},
    {HE_English_395, Route103_Text_MayTimeToHeadBack},
    {HE_English_395, Route103_Text_BrendanTimeToHeadBack},
    {HE_English_396, SlateportCity_Harbor_Text_SameThugsTriedToRobAtMuseum},
    {HE_English_397, SlateportCity_Harbor_Text_ArchieYouAgainHideoutInLilycove},
    {HE_English_398, SlateportCity_Harbor_Text_CaptSternWhyStealMySubmarine},
    {HE_English_399, SlateportCity_Harbor_Text_TeamAquaLeftNeedDive},
    {HE_English_400, SlateportCity_Harbor_Text_NeedDiveToCatchSub},
    {HE_English_401, Route110_Text_MayLetsBattle},
    {HE_English_401, Route110_Text_BrendanLetsBattle},
    {HE_English_402, Route110_Text_MayDefeated},
    {HE_English_402, Route110_Text_BrendanDefeated},
    {HE_English_403, Route110_Text_MayTakeThis},
    {HE_English_403, Route110_Text_BrendanTakeThis},
    {HE_English_404, Route110_Text_MayExplainItemfinder},
    {HE_English_404, Route110_Text_BrendanExplainItemfinder},
    {HE_English_405, Route110_Text_ImagineSeeingYouHere},
    {HE_English_406, Route110_Text_HeardYouInstallMatchCall},
    {HE_English_407, Route110_Text_KeepAnEyeOutForRival},
    {HE_English_408, LilycoveCity_Text_ChanceToDoBigThings},
    {HE_English_409, LilycoveCity_Text_IfWorldBecomesOurs},
    {HE_English_410, LilycoveCity_Text_TeamAquaBeenTrainingWailmer},
    {HE_English_411, LilycoveCity_Text_SomeonePuntedTeamAquaOut},
    {HE_English_412, LilycoveCity_Text_TeamAquaRenovatedCavern},
    {HE_English_413, LilycoveCity_Text_TeamAquaLotGoneForGood},
    {HE_English_414, PetalburgWoods_Text_NotAOneToBeFound},
    {HE_English_415, PetalburgWoods_Text_HaveYouSeenShroomish},
    {HE_English_416, PetalburgWoods_Text_IWasGoingToAmbushYou},
    {HE_English_417, PetalburgWoods_Text_NoOneCrossesTeamAqua},
    {HE_English_418, PetalburgWoods_Text_YoureKiddingMe},
    {HE_English_419, PetalburgWoods_Text_YouveGotSomeNerve},
    {HE_English_420, PetalburgWoods_Text_ThatWasAwfullyClose},
    {HE_English_421, PetalburgWoods_Text_TeamAquaAfterSomethingInRustboro},
    {HE_English_422, PetalburgWoods_Text_ICantBeWastingTime},
    {HE_English_423, PetalburgWoods_Text_YoureLoadedWithItems},
    {HE_English_424, PetalburgWoods_Text_ImOutOfPokeBalls},
    {HE_English_425, PetalburgWoods_Text_InstantlyPopularWithBugPokemon},
    {HE_English_426, PetalburgWoods_Text_CantBePopularIfILose},
    {HE_English_427, PetalburgWoods_Text_PeopleRespectYou},
    {HE_English_428, PetalburgWoods_Text_StayOutOfTallGrass},
    {HE_English_429, PetalburgWoods_Text_HiddenItemsExplanation},
    {HE_English_430, RustboroCity_Gym_Text_GymGuideAdvice},
    {HE_English_431, RustboroCity_Gym_Text_GymGuidePostVictory},
    {HE_English_432, RustboroCity_Gym_Text_JoshIntro},
    {HE_English_433, RustboroCity_Gym_Text_JoshPostBattle},
    {HE_English_434, RustboroCity_Gym_Text_TommyIntro},
    {HE_English_435, RustboroCity_Gym_Text_TommyDefeat},
    {HE_English_436, RustboroCity_Gym_Text_TommyPostBattle},
    {HE_English_437, RustboroCity_Gym_Text_MarcIntro},
    {HE_English_438, RustboroCity_Gym_Text_MarcDefeat},
    {HE_English_439, RustboroCity_Gym_Text_MarcPostBattle},
    {HE_English_440, RustboroCity_Gym_Text_RoxanneIntro},
    {HE_English_441, RustboroCity_Gym_Text_RoxanneDefeat},
    {HE_English_442, RustboroCity_Gym_Text_ReceivedStoneBadge},
    {HE_English_443, RustboroCity_Gym_Text_StoneBadgeInfoTakeThis},
    {HE_English_444, RustboroCity_Gym_Text_ExplainRockTomb},
    {HE_English_445, RustboroCity_Gym_Text_RoxannePostBattle},
    {HE_English_446, RustboroCity_Gym_Text_GymStatue},
    {HE_English_447, RustboroCity_Gym_Text_GymStatueCertified},
    {HE_English_448, HE_Text_NoProof},
    {HE_English_449, HE_Text_Radio},
    {HE_English_450, HE_Text_RoxanneResistance},
    {HE_English_451, HE_Text_EndChapter},
    {HE_English_452, PetalburgCity_Text_WhereIsWally},
    {HE_English_453, PetalburgCity_Text_AreYouRookieTrainer},
    {HE_English_454, PetalburgCity_Text_ThisIsPetalburgGym},
    {HE_English_455, PetalburgCity_Text_ThisIsGymSign},
    {HE_English_456, PetalburgCity_Text_WaterReflection},
    {HE_English_457, PetalburgCity_Text_FullPartyExplanation},
    {HE_English_458, PetalburgCity_Text_AreYouATrainer},
    {HE_English_459, PetalburgCity_Text_WellMaybeNot},
    {HE_English_460, PetalburgCity_Text_ImLookingForTalentedTrainers},
    {HE_English_461, SlateportCity_Text_AquaHasPolicy},
    {HE_English_462, SlateportCity_Text_AquaWillAssumeControlOfSubmarine},
    {HE_English_463, SlateportCity_Text_SternWhatWasAllThat},
    {HE_English_464, SlateportCity_Text_FromHarborTryingToTakeSub},
    {HE_English_465, Route109_Text_YouCanHaveThis},
    {HE_English_466, Route101_Text_PleaseHelp},
    {HE_English_467, Route101_Text_DontLeaveMe},
    {HE_English_468, Route101_Text_YouSavedMe},
    {HE_English_469, Route101_Text_TakeTiredPokemonToPokeCenter},
    {HE_English_470, Route102_Text_LetsGoBack},
    {HE_English_471, Route102_Text_ImNotVeryTall},
    {HE_English_472, Route102_Text_CatchWholeBunchOfPokemon},
    {HE_English_473, DewfordTown_Text_TinyIslandCommunity},
    {HE_English_474, DewfordTown_Text_PetalburgWereSettingSail2},
    {HE_English_475, DewfordTown_Text_GoDeliverIllBeWaiting},
    {HE_English_476, DewfordTown_Text_SlateportWereSettingSail},
    {HE_English_477, DewfordTown_Text_GettingItchToFish},
    {HE_English_478, DewfordTown_Text_GiveYouOneOfMyRods},
    {HE_English_479, DewfordTown_Text_ThrowInFishingAdvice},
    {HE_English_480, DewfordTown_Text_ThatsTooBadThen},
    {HE_English_481, DewfordTown_Text_GreatHaulInSomeBigOnes},
    {HE_English_482, DewfordTown_Text_FishingAdvice},
    {HE_English_483, HE_Text_DewfordArrival},
    {HE_English_484, gText_Birch_Welcome},
    {HE_English_485, gText_Birch_Pokemon},
    {HE_English_486, gText_Birch_MainSpeech},
    {HE_English_487, gText_Birch_AndYouAre},
    {HE_English_488, gText_Birch_BoyOrGirl},
    {HE_English_489, gText_Birch_WhatsYourName},
    {HE_English_490, gText_Birch_SoItsPlayer},
    {HE_English_491, gText_Birch_YourePlayer},
    {HE_English_492, gText_Birch_AreYouReady},
    {HE_English_493, DewfordTown_Text_WhereAreWeBound},
    {HE_English_494, LittlerootTown_ProfessorBirchsLab_Text_ReceivedPokedex},
    {HE_English_495, MauvilleCity_Text_WallyPleaseBattleMe},
    {HE_English_496, MtChimney_Text_PlayerRemovedMeteorite},
    {HE_English_497, OldaleTown_Text_PotionExplanation},
    {HE_English_498, PetalburgCity_Gym_Text_WallyIdLikeAPokemon},
    {HE_English_499, PetalburgCity_Gym_Text_WallyOhWowThankYou},
    {HE_English_500, PetalburgCity_Gym_Text_WouldYouReallyComeWithMe},
    {HE_English_501, Route104_MrBrineysHouse_Text_WhereAreWeBound},
    {HE_English_502, Route109_Text_BrineyWhereAreWeBound},
    {HE_English_503, Route119_WeatherInstitute_2F_Text_PlayerReceivedCastform},
    {HE_English_504, RustboroCity_Gym_Text_JoshDefeat},
    {HE_English_505, SootopolisCity_Text_SootopolisDidntGetWrecked},
};
